/**
 * 图标映射工具
 * 统一管理 Sidebar 使用的图标
 */

import {
  LayoutDashboard,
  FileText,
  AlertCircle,
  HelpCircle,
  BarChart3,
  Database,
  Book,
  Calendar,
  GitMerge,
  Shield,
  TrendingUp,
  Rocket,
  Monitor,
  Key,
  Workflow,
  Play,
  Settings,
  History,
  Users,
  User,
  Activity,
  Clock,
  ClipboardList,
  Bot,
  MessageSquare,
  Sparkles,
  Lightbulb,
  Send,
  CheckSquare,
  RotateCcw,
  ArrowRight,
  Folder,
  Target,
  Wrench,
  ArrowLeftRight,
  AlertTriangle,
  CheckCircle,
  Zap,
  Tag,
  Link,
  Lock,
  Bell,
  Cloud,
  Boxes,
  RefreshCw,
  Server,
  GitBranch,
  List,
  BookOpen,
  ArrowUpCircle,
  Plus,
  Building,
  Search,
  Edit,
} from 'lucide-react';

// 图标样式
export const iconStyle = { width: 16, height: 16 } as const;

// 图标映射表
export const iconMap: Record<string, React.ReactNode> = {
  LayoutDashboard: <LayoutDashboard style={iconStyle} />,
  FileText: <FileText style={iconStyle} />,
  AlertCircle: <AlertCircle style={iconStyle} />,
  HelpCircle: <HelpCircle style={iconStyle} />,
  BarChart3: <BarChart3 style={iconStyle} />,
  Database: <Database style={iconStyle} />,
  Book: <Book style={iconStyle} />,
  Calendar: <Calendar style={iconStyle} />,
  GitMerge: <GitMerge style={iconStyle} />,
  Shield: <Shield style={iconStyle} />,
  TrendingUp: <TrendingUp style={iconStyle} />,
  Rocket: <Rocket style={iconStyle} />,
  Monitor: <Monitor style={iconStyle} />,
  Key: <Key style={iconStyle} />,
  Workflow: <Workflow style={iconStyle} />,
  Play: <Play style={iconStyle} />,
  Settings: <Settings style={iconStyle} />,
  History: <History style={iconStyle} />,
  Users: <Users style={iconStyle} />,
  User: <User style={iconStyle} />,
  Activity: <Activity style={iconStyle} />,
  Clock: <Clock style={iconStyle} />,
  ClipboardList: <ClipboardList style={iconStyle} />,
  Bot: <Bot style={iconStyle} />,
  MessageSquare: <MessageSquare style={iconStyle} />,
  Sparkles: <Sparkles style={iconStyle} />,
  Lightbulb: <Lightbulb style={iconStyle} />,
  Send: <Send style={iconStyle} />,
  CheckSquare: <CheckSquare style={iconStyle} />,
  RotateCcw: <RotateCcw style={iconStyle} />,
  ArrowRight: <ArrowRight style={iconStyle} />,
  Folder: <Folder style={iconStyle} />,
  Target: <Target style={iconStyle} />,
  Wrench: <Wrench style={iconStyle} />,
  ArrowLeftRight: <ArrowLeftRight style={iconStyle} />,
  AlertTriangle: <AlertTriangle style={iconStyle} />,
  CheckCircle: <CheckCircle style={iconStyle} />,
  Zap: <Zap style={iconStyle} />,
  Tag: <Tag style={iconStyle} />,
  Link: <Link style={iconStyle} />,
  Lock: <Lock style={iconStyle} />,
  Bell: <Bell style={iconStyle} />,
  Cloud: <Cloud style={iconStyle} />,
  Boxes: <Boxes style={iconStyle} />,
  RefreshCw: <RefreshCw style={iconStyle} />,
  Server: <Server style={iconStyle} />,
  GitBranch: <GitBranch style={iconStyle} />,
  List: <List style={iconStyle} />,
  BookOpen: <BookOpen style={iconStyle} />,
  ArrowUpCircle: <ArrowUpCircle style={iconStyle} />,
  Plus: <Plus style={iconStyle} />,
  Building: <Building style={iconStyle} />,
  Search: <Search style={iconStyle} />,
  Edit: <Edit style={iconStyle} />,
};

/**
 * 根据图标名称获取图标组件
 */
export function getIconByName(iconName?: string): React.ReactNode | undefined {
  if (!iconName) return undefined;
  return iconMap[iconName];
}
