// Code generated by ent, DO NOT EDIT.

package configurationitemhistory

import (
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldID, id))
}

// CiID applies equality check predicate on the "ci_id" field. It's identical to CiIDEQ.
func CiID(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldCiID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldVersion, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperation, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorName applies equality check predicate on the "operator_name" field. It's identical to OperatorNameEQ.
func OperatorName(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperatorName, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldRemark, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CiIDEQ applies the EQ predicate on the "ci_id" field.
func CiIDEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldCiID, v))
}

// CiIDNEQ applies the NEQ predicate on the "ci_id" field.
func CiIDNEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldCiID, v))
}

// CiIDIn applies the In predicate on the "ci_id" field.
func CiIDIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldCiID, vs...))
}

// CiIDNotIn applies the NotIn predicate on the "ci_id" field.
func CiIDNotIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldCiID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldVersion, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContainsFold(FieldOperation, v))
}

// BeforeIsNil applies the IsNil predicate on the "before" field.
func BeforeIsNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIsNull(FieldBefore))
}

// BeforeNotNil applies the NotNil predicate on the "before" field.
func BeforeNotNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotNull(FieldBefore))
}

// AfterIsNil applies the IsNil predicate on the "after" field.
func AfterIsNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIsNull(FieldAfter))
}

// AfterNotNil applies the NotNil predicate on the "after" field.
func AfterNotNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotNull(FieldAfter))
}

// ChangedFieldsIsNil applies the IsNil predicate on the "changed_fields" field.
func ChangedFieldsIsNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIsNull(FieldChangedFields))
}

// ChangedFieldsNotNil applies the NotNil predicate on the "changed_fields" field.
func ChangedFieldsNotNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotNull(FieldChangedFields))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorNameEQ applies the EQ predicate on the "operator_name" field.
func OperatorNameEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldOperatorName, v))
}

// OperatorNameNEQ applies the NEQ predicate on the "operator_name" field.
func OperatorNameNEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldOperatorName, v))
}

// OperatorNameIn applies the In predicate on the "operator_name" field.
func OperatorNameIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldOperatorName, vs...))
}

// OperatorNameNotIn applies the NotIn predicate on the "operator_name" field.
func OperatorNameNotIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldOperatorName, vs...))
}

// OperatorNameGT applies the GT predicate on the "operator_name" field.
func OperatorNameGT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldOperatorName, v))
}

// OperatorNameGTE applies the GTE predicate on the "operator_name" field.
func OperatorNameGTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldOperatorName, v))
}

// OperatorNameLT applies the LT predicate on the "operator_name" field.
func OperatorNameLT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldOperatorName, v))
}

// OperatorNameLTE applies the LTE predicate on the "operator_name" field.
func OperatorNameLTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldOperatorName, v))
}

// OperatorNameContains applies the Contains predicate on the "operator_name" field.
func OperatorNameContains(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContains(FieldOperatorName, v))
}

// OperatorNameHasPrefix applies the HasPrefix predicate on the "operator_name" field.
func OperatorNameHasPrefix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasPrefix(FieldOperatorName, v))
}

// OperatorNameHasSuffix applies the HasSuffix predicate on the "operator_name" field.
func OperatorNameHasSuffix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasSuffix(FieldOperatorName, v))
}

// OperatorNameIsNil applies the IsNil predicate on the "operator_name" field.
func OperatorNameIsNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIsNull(FieldOperatorName))
}

// OperatorNameNotNil applies the NotNil predicate on the "operator_name" field.
func OperatorNameNotNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotNull(FieldOperatorName))
}

// OperatorNameEqualFold applies the EqualFold predicate on the "operator_name" field.
func OperatorNameEqualFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEqualFold(FieldOperatorName, v))
}

// OperatorNameContainsFold applies the ContainsFold predicate on the "operator_name" field.
func OperatorNameContainsFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContainsFold(FieldOperatorName, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldContainsFold(FieldRemark, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCi applies the HasEdge predicate on the "ci" edge.
func HasCi() predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CiTable, CiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCiWith applies the HasEdge predicate on the "ci" edge with a given conditions (other predicates).
func HasCiWith(preds ...predicate.ConfigurationItem) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(func(s *sql.Selector) {
		step := newCiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConfigurationItemHistory) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConfigurationItemHistory) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConfigurationItemHistory) predicate.ConfigurationItemHistory {
	return predicate.ConfigurationItemHistory(sql.NotPredicates(p))
}
