version: 2

updates:
  - package-ecosystem: gomod
    directory: /itsm-backend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: npm
    directory: /itsm-frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
