package middleware

// precheckFallbackPolicies 显式族级回退预检策略（2026-09-17 批次 5）。
//
// 与 rbac_precheck_gen.go（从路由声明生成）合并构成 ResourceActionMap：
//
//	ResourceActionMap = 生成条目（路由声明，精确路径） + 本文件（族级通配/别名策略）
//
// 本文件承载的是**策略**而非路由声明的复制：
//   - 族级通配（如 POST /api/v1/changes/* = change:write）：为未声明/未来新增的
//     子路径提供 fail-closed 缺省预检；
//   - 历史别名与仅 AuthMiddleware 的路由（如 /api/v1/auth/*、
//     /configuration-items/* 兼容别名）：保留批次 3 之前的既定预检口径。
//
// 匹配优先级：getPermissionFromPath 先精确后通配、按 specificity 取最具体，
// 因此生成条目（精确路径）天然优先于本文件的族级通配。
// 修改口径 = 直接编辑本文件并跑 TestRoutePrecheckAlignment 验证。
var precheckFallbackPolicies = map[string]map[string]Permission{
	"DELETE": {
		"/api/v1/applications/*":       {Resource: "application", Action: "write"},
		"/api/v1/bpmn/*":               {Resource: "bpmn", Action: "delete"},
		"/api/v1/cloud/*":              {Resource: "cmdb", Action: "write"},
		"/api/v1/cmdb/*":               {Resource: "cmdb", Action: "delete"},
		"/api/v1/connectors/*":         {Resource: "connector", Action: "write"},
		"/api/v1/dashboard/*":          {Resource: "dashboard", Action: "admin"},
		"/api/v1/knowledge-articles/*": {Resource: "knowledge", Action: "delete"},
		"/api/v1/knowledge/*":          {Resource: "knowledge", Action: "delete"},
		"/api/v1/surveys/*":            {Resource: "survey", Action: "write"},
		"/api/v1/ticket-templates/*":   {Resource: "ticket_template", Action: "delete"},
	},
	"GET": {
		"/api/v1/agent/*":              {Resource: "ai", Action: "read"},
		"/api/v1/ai/*":                 {Resource: "ai", Action: "read"},
		"/api/v1/applications/*":       {Resource: "application", Action: "read"},
		"/api/v1/audit-logs":           {Resource: "audit", Action: "read"},
		"/api/v1/auth/me":              {Resource: "user", Action: "read"},
		"/api/v1/auth/menus":           {Resource: "user", Action: "read"},
		"/api/v1/auth/profile":         {Resource: "user", Action: "read"},
		"/api/v1/bpmn/*":               {Resource: "bpmn", Action: "read"},
		"/api/v1/cloud":                {Resource: "cmdb", Action: "read"},
		"/api/v1/cloud/*":              {Resource: "cmdb", Action: "read"},
		"/api/v1/cmdb":                 {Resource: "cmdb", Action: "read"},
		"/api/v1/cmdb/*":               {Resource: "cmdb", Action: "read"},
		"/api/v1/connectors/*":         {Resource: "connector", Action: "read"},
		"/api/v1/dashboard/*":          {Resource: "dashboard", Action: "read"},
		"/api/v1/departments":          {Resource: "department", Action: "read"},
		"/api/v1/departments/*":        {Resource: "department", Action: "read"},
		"/api/v1/knowledge/*":          {Resource: "knowledge", Action: "read"},
		"/api/v1/msp/customers/*":      {Resource: "msp_customer", Action: "read"},
		"/api/v1/msp/reports/*":        {Resource: "msp_report", Action: "read"},
		"/api/v1/msp/status":           {Resource: "msp", Action: "read"},
		"/api/v1/notifications/*":      {Resource: "notification", Action: "read"},
		"/api/v1/org/*":                {Resource: "org", Action: "read"},
		"/api/v1/process-trigger/*":    {Resource: "bpmn", Action: "read"},
		"/api/v1/provisioning-tasks/*": {Resource: "service_request", Action: "read"},
		"/api/v1/reports/*":            {Resource: "dashboard", Action: "read"},
		"/api/v1/service-catalog":      {Resource: "service_catalog", Action: "read"},
		"/api/v1/sla/*":                {Resource: "sla", Action: "read"},
		"/api/v1/system/*":             {Resource: "system_config", Action: "read"},
		"/api/v1/ticket-templates":     {Resource: "ticket_template", Action: "read"},
		"/api/v1/ticket-templates/*":   {Resource: "ticket_template", Action: "read"},
		"/api/v1/workflow/tasks/*":     {Resource: "task", Action: "read"},
	},
	"PATCH": {
		"/api/v1/applications/*":       {Resource: "application", Action: "write"},
		"/api/v1/bpmn/*":               {Resource: "bpmn", Action: "write"},
		"/api/v1/bpmn/tasks/*":         {Resource: "task", Action: "update"},
		"/api/v1/changes/*":            {Resource: "change", Action: "write"},
		"/api/v1/cloud/*":              {Resource: "cmdb", Action: "write"},
		"/api/v1/cmdb/*":               {Resource: "cmdb", Action: "write"},
		"/api/v1/connectors/*":         {Resource: "connector", Action: "write"},
		"/api/v1/dashboard/*":          {Resource: "dashboard", Action: "admin"},
		"/api/v1/incidents/*":          {Resource: "incident", Action: "write"},
		"/api/v1/knowledge-articles/*": {Resource: "knowledge", Action: "write"},
		"/api/v1/knowledge/*":          {Resource: "knowledge", Action: "write"},
		"/api/v1/menus/*":              {Resource: "system_config", Action: "write"},
		"/api/v1/notifications/*":      {Resource: "notification", Action: "write"},
		"/api/v1/problems/*":           {Resource: "problem", Action: "write"},
		"/api/v1/releases/*":           {Resource: "release", Action: "write"},
		"/api/v1/service-catalogs/*":   {Resource: "service_catalog", Action: "write"},
		"/api/v1/service-requests/*":   {Resource: "service_request", Action: "write"},
		"/api/v1/surveys/*":            {Resource: "survey", Action: "write"},
		"/api/v1/tenants/*":            {Resource: "tenant", Action: "write"},
		"/api/v1/ticket-categories/*":  {Resource: "ticket_category", Action: "write"},
		"/api/v1/ticket-tags/*":        {Resource: "ticket_tag", Action: "write"},
		"/api/v1/ticket-templates/*":   {Resource: "ticket_template", Action: "write"},
		"/api/v1/users/*":              {Resource: "user", Action: "write"},
		"/api/v1/vendors/*":            {Resource: "vendor", Action: "write"},
		"/api/v1/workflow/tasks/*":     {Resource: "task", Action: "update"},
	},
	"POST": {
		"/api/v1/admin/operations/commands/*": {Resource: "system", Action: "write"},
		"/api/v1/agent/*":                     {Resource: "ai", Action: "write"},
		"/api/v1/ai/*":                        {Resource: "ai", Action: "write"},
		"/api/v1/applications/*":              {Resource: "application", Action: "write"},
		"/api/v1/bpmn/*":                      {Resource: "bpmn", Action: "write"},
		"/api/v1/bpmn/tasks/*":                {Resource: "task", Action: "update"},
		"/api/v1/changes/*":                   {Resource: "change", Action: "write"},
		"/api/v1/cloud":                       {Resource: "cmdb", Action: "write"},
		"/api/v1/cloud/*":                     {Resource: "cmdb", Action: "write"},
		"/api/v1/cmdb":                        {Resource: "cmdb", Action: "write"},
		"/api/v1/cmdb/*":                      {Resource: "cmdb", Action: "write"},
		"/api/v1/configuration-items/*":       {Resource: "cmdb", Action: "write"},
		"/api/v1/connectors":                  {Resource: "connector", Action: "write"},
		"/api/v1/connectors/*":                {Resource: "connector", Action: "write"},
		"/api/v1/dashboard/*":                 {Resource: "dashboard", Action: "admin"},
		"/api/v1/incidents/*":                 {Resource: "incident", Action: "write"},
		"/api/v1/knowledge-articles/*":        {Resource: "knowledge", Action: "write"},
		"/api/v1/knowledge/articles/*":        {Resource: "knowledge", Action: "write"},
		"/api/v1/menus/*":                     {Resource: "system_config", Action: "write"},
		"/api/v1/org/*":                       {Resource: "org", Action: "write"},
		"/api/v1/problems/*":                  {Resource: "problem", Action: "write"},
		"/api/v1/process-bindings/*":          {Resource: "bpmn", Action: "write"},
		"/api/v1/process-trigger/*":           {Resource: "bpmn", Action: "write"},
		"/api/v1/provisioning-tasks/*":        {Resource: "service_request", Action: "write"},
		"/api/v1/releases/*":                  {Resource: "release", Action: "write"},
		"/api/v1/reports":                     {Resource: "dashboard", Action: "admin"},
		"/api/v1/reports/*":                   {Resource: "dashboard", Action: "admin"},
		"/api/v1/roles/*":                     {Resource: "role", Action: "write"},
		"/api/v1/service-catalogs/*":          {Resource: "service_catalog", Action: "write"},
		"/api/v1/service-requests/*":          {Resource: "service_request", Action: "write"},
		"/api/v1/sla/*":                       {Resource: "sla", Action: "write"},
		"/api/v1/surveys/*":                   {Resource: "survey", Action: "write"},
		"/api/v1/system/*":                    {Resource: "system_config", Action: "write"},
		"/api/v1/tenants/*":                   {Resource: "tenant", Action: "write"},
		"/api/v1/ticket-categories/*":         {Resource: "ticket_category", Action: "write"},
		"/api/v1/ticket-tags/*":               {Resource: "ticket_tag", Action: "write"},
		"/api/v1/ticket-templates":            {Resource: "ticket_template", Action: "write"},
		"/api/v1/ticket-templates/*":          {Resource: "ticket_template", Action: "write"},
		"/api/v1/tickets/*":                   {Resource: "ticket", Action: "write"},
		"/api/v1/vendors/*":                   {Resource: "vendor", Action: "write"},
		"/api/v1/workflow/tasks/*":            {Resource: "task", Action: "update"},
	},
	"PUT": {
		"/api/v1/applications/*":       {Resource: "application", Action: "write"},
		"/api/v1/bpmn/*":               {Resource: "bpmn", Action: "write"},
		"/api/v1/bpmn/tasks/*":         {Resource: "task", Action: "update"},
		"/api/v1/cloud/*":              {Resource: "cmdb", Action: "write"},
		"/api/v1/cmdb/*":               {Resource: "cmdb", Action: "write"},
		"/api/v1/connectors/*":         {Resource: "connector", Action: "write"},
		"/api/v1/dashboard/*":          {Resource: "dashboard", Action: "admin"},
		"/api/v1/knowledge-articles/*": {Resource: "knowledge", Action: "write"},
		"/api/v1/knowledge/*":          {Resource: "knowledge", Action: "write"},
		"/api/v1/notifications/*":      {Resource: "notification", Action: "write"},
		"/api/v1/ticket-templates/*":   {Resource: "ticket_template", Action: "write"},
		"/api/v1/vendors/*":            {Resource: "vendor", Action: "write"},
		"/api/v1/workflow/tasks/*":     {Resource: "task", Action: "update"},
	},
}
