// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"itsm-backend/ent/approvalworkflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ApprovalWorkflow is the model entity for the ApprovalWorkflow schema.
type ApprovalWorkflow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 工作流名称
	Name string `json:"name,omitempty"`
	// 工作流描述
	Description string `json:"description,omitempty"`
	// 工单类型
	TicketType string `json:"ticket_type,omitempty"`
	// 优先级
	Priority string `json:"priority,omitempty"`
	// 审批节点配置
	Nodes []map[string]interface{} `json:"nodes,omitempty"`
	// 是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 租户ID
	TenantID int `json:"tenant_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApprovalWorkflowQuery when eager-loading is set.
	Edges        ApprovalWorkflowEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApprovalWorkflowEdges holds the relations/edges for other nodes in the graph.
type ApprovalWorkflowEdges struct {
	// 审批记录
	ApprovalRecords []*ApprovalRecord `json:"approval_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ApprovalRecordsOrErr returns the ApprovalRecords value or an error if the edge
// was not loaded in eager-loading.
func (e ApprovalWorkflowEdges) ApprovalRecordsOrErr() ([]*ApprovalRecord, error) {
	if e.loadedTypes[0] {
		return e.ApprovalRecords, nil
	}
	return nil, &NotLoadedError{edge: "approval_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApprovalWorkflow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case approvalworkflow.FieldNodes:
			values[i] = new([]byte)
		case approvalworkflow.FieldIsActive:
			values[i] = new(sql.NullBool)
		case approvalworkflow.FieldID, approvalworkflow.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case approvalworkflow.FieldName, approvalworkflow.FieldDescription, approvalworkflow.FieldTicketType, approvalworkflow.FieldPriority:
			values[i] = new(sql.NullString)
		case approvalworkflow.FieldCreatedAt, approvalworkflow.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApprovalWorkflow fields.
func (aw *ApprovalWorkflow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case approvalworkflow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			aw.ID = int(value.Int64)
		case approvalworkflow.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				aw.Name = value.String
			}
		case approvalworkflow.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				aw.Description = value.String
			}
		case approvalworkflow.FieldTicketType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_type", values[i])
			} else if value.Valid {
				aw.TicketType = value.String
			}
		case approvalworkflow.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				aw.Priority = value.String
			}
		case approvalworkflow.FieldNodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nodes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &aw.Nodes); err != nil {
					return fmt.Errorf("unmarshal field nodes: %w", err)
				}
			}
		case approvalworkflow.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				aw.IsActive = value.Bool
			}
		case approvalworkflow.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				aw.TenantID = int(value.Int64)
			}
		case approvalworkflow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aw.CreatedAt = value.Time
			}
		case approvalworkflow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aw.UpdatedAt = value.Time
			}
		default:
			aw.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApprovalWorkflow.
// This includes values selected through modifiers, order, etc.
func (aw *ApprovalWorkflow) Value(name string) (ent.Value, error) {
	return aw.selectValues.Get(name)
}

// QueryApprovalRecords queries the "approval_records" edge of the ApprovalWorkflow entity.
func (aw *ApprovalWorkflow) QueryApprovalRecords() *ApprovalRecordQuery {
	return NewApprovalWorkflowClient(aw.config).QueryApprovalRecords(aw)
}

// Update returns a builder for updating this ApprovalWorkflow.
// Note that you need to call ApprovalWorkflow.Unwrap() before calling this method if this ApprovalWorkflow
// was returned from a transaction, and the transaction was committed or rolled back.
func (aw *ApprovalWorkflow) Update() *ApprovalWorkflowUpdateOne {
	return NewApprovalWorkflowClient(aw.config).UpdateOne(aw)
}

// Unwrap unwraps the ApprovalWorkflow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aw *ApprovalWorkflow) Unwrap() *ApprovalWorkflow {
	_tx, ok := aw.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApprovalWorkflow is not a transactional entity")
	}
	aw.config.driver = _tx.drv
	return aw
}

// String implements the fmt.Stringer.
func (aw *ApprovalWorkflow) String() string {
	var builder strings.Builder
	builder.WriteString("ApprovalWorkflow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aw.ID))
	builder.WriteString("name=")
	builder.WriteString(aw.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(aw.Description)
	builder.WriteString(", ")
	builder.WriteString("ticket_type=")
	builder.WriteString(aw.TicketType)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(aw.Priority)
	builder.WriteString(", ")
	builder.WriteString("nodes=")
	builder.WriteString(fmt.Sprintf("%v", aw.Nodes))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", aw.IsActive))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", aw.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(aw.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aw.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ApprovalWorkflows is a parsable slice of ApprovalWorkflow.
type ApprovalWorkflows []*ApprovalWorkflow
