// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"itsm-backend/ent/approvallog"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/ticket"
	"itsm-backend/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApprovalLogQuery is the builder for querying ApprovalLog entities.
type ApprovalLogQuery struct {
	config
	ctx          *QueryContext
	order        []approvallog.OrderOption
	inters       []Interceptor
	predicates   []predicate.ApprovalLog
	withApprover *UserQuery
	withTicket   *TicketQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApprovalLogQuery builder.
func (alq *ApprovalLogQuery) Where(ps ...predicate.ApprovalLog) *ApprovalLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *ApprovalLogQuery) Limit(limit int) *ApprovalLogQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *ApprovalLogQuery) Offset(offset int) *ApprovalLogQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *ApprovalLogQuery) Unique(unique bool) *ApprovalLogQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *ApprovalLogQuery) Order(o ...approvallog.OrderOption) *ApprovalLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// QueryApprover chains the current query on the "approver" edge.
func (alq *ApprovalLogQuery) QueryApprover() *UserQuery {
	query := (&UserClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approvallog.Table, approvallog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approvallog.ApproverTable, approvallog.ApproverColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTicket chains the current query on the "ticket" edge.
func (alq *ApprovalLogQuery) QueryTicket() *TicketQuery {
	query := (&TicketClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approvallog.Table, approvallog.FieldID, selector),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approvallog.TicketTable, approvallog.TicketColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ApprovalLog entity from the query.
// Returns a *NotFoundError when no ApprovalLog was found.
func (alq *ApprovalLogQuery) First(ctx context.Context) (*ApprovalLog, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{approvallog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *ApprovalLogQuery) FirstX(ctx context.Context) *ApprovalLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApprovalLog ID from the query.
// Returns a *NotFoundError when no ApprovalLog ID was found.
func (alq *ApprovalLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{approvallog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *ApprovalLogQuery) FirstIDX(ctx context.Context) int {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApprovalLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApprovalLog entity is found.
// Returns a *NotFoundError when no ApprovalLog entities are found.
func (alq *ApprovalLogQuery) Only(ctx context.Context) (*ApprovalLog, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{approvallog.Label}
	default:
		return nil, &NotSingularError{approvallog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *ApprovalLogQuery) OnlyX(ctx context.Context) *ApprovalLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApprovalLog ID in the query.
// Returns a *NotSingularError when more than one ApprovalLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *ApprovalLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{approvallog.Label}
	default:
		err = &NotSingularError{approvallog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *ApprovalLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApprovalLogs.
func (alq *ApprovalLogQuery) All(ctx context.Context) ([]*ApprovalLog, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryAll)
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApprovalLog, *ApprovalLogQuery]()
	return withInterceptors[[]*ApprovalLog](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *ApprovalLogQuery) AllX(ctx context.Context) []*ApprovalLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApprovalLog IDs.
func (alq *ApprovalLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryIDs)
	if err = alq.Select(approvallog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *ApprovalLogQuery) IDsX(ctx context.Context) []int {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *ApprovalLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryCount)
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*ApprovalLogQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *ApprovalLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *ApprovalLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryExist)
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *ApprovalLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApprovalLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *ApprovalLogQuery) Clone() *ApprovalLogQuery {
	if alq == nil {
		return nil
	}
	return &ApprovalLogQuery{
		config:       alq.config,
		ctx:          alq.ctx.Clone(),
		order:        append([]approvallog.OrderOption{}, alq.order...),
		inters:       append([]Interceptor{}, alq.inters...),
		predicates:   append([]predicate.ApprovalLog{}, alq.predicates...),
		withApprover: alq.withApprover.Clone(),
		withTicket:   alq.withTicket.Clone(),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// WithApprover tells the query-builder to eager-load the nodes that are connected to
// the "approver" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *ApprovalLogQuery) WithApprover(opts ...func(*UserQuery)) *ApprovalLogQuery {
	query := (&UserClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withApprover = query
	return alq
}

// WithTicket tells the query-builder to eager-load the nodes that are connected to
// the "ticket" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *ApprovalLogQuery) WithTicket(opts ...func(*TicketQuery)) *ApprovalLogQuery {
	query := (&TicketClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withTicket = query
	return alq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ApproverID int `json:"approver_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApprovalLog.Query().
//		GroupBy(approvallog.FieldApproverID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (alq *ApprovalLogQuery) GroupBy(field string, fields ...string) *ApprovalLogGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApprovalLogGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = approvallog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ApproverID int `json:"approver_id,omitempty"`
//	}
//
//	client.ApprovalLog.Query().
//		Select(approvallog.FieldApproverID).
//		Scan(ctx, &v)
func (alq *ApprovalLogQuery) Select(fields ...string) *ApprovalLogSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &ApprovalLogSelect{ApprovalLogQuery: alq}
	sbuild.label = approvallog.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApprovalLogSelect configured with the given aggregations.
func (alq *ApprovalLogQuery) Aggregate(fns ...AggregateFunc) *ApprovalLogSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *ApprovalLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !approvallog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *ApprovalLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApprovalLog, error) {
	var (
		nodes       = []*ApprovalLog{}
		_spec       = alq.querySpec()
		loadedTypes = [2]bool{
			alq.withApprover != nil,
			alq.withTicket != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApprovalLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApprovalLog{config: alq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := alq.withApprover; query != nil {
		if err := alq.loadApprover(ctx, query, nodes, nil,
			func(n *ApprovalLog, e *User) { n.Edges.Approver = e }); err != nil {
			return nil, err
		}
	}
	if query := alq.withTicket; query != nil {
		if err := alq.loadTicket(ctx, query, nodes, nil,
			func(n *ApprovalLog, e *Ticket) { n.Edges.Ticket = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (alq *ApprovalLogQuery) loadApprover(ctx context.Context, query *UserQuery, nodes []*ApprovalLog, init func(*ApprovalLog), assign func(*ApprovalLog, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ApprovalLog)
	for i := range nodes {
		fk := nodes[i].ApproverID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "approver_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (alq *ApprovalLogQuery) loadTicket(ctx context.Context, query *TicketQuery, nodes []*ApprovalLog, init func(*ApprovalLog), assign func(*ApprovalLog, *Ticket)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ApprovalLog)
	for i := range nodes {
		fk := nodes[i].TicketID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ticket.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ticket_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (alq *ApprovalLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *ApprovalLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(approvallog.Table, approvallog.Columns, sqlgraph.NewFieldSpec(approvallog.FieldID, field.TypeInt))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approvallog.FieldID)
		for i := range fields {
			if fields[i] != approvallog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if alq.withApprover != nil {
			_spec.Node.AddColumnOnce(approvallog.FieldApproverID)
		}
		if alq.withTicket != nil {
			_spec.Node.AddColumnOnce(approvallog.FieldTicketID)
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *ApprovalLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(approvallog.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = approvallog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApprovalLogGroupBy is the group-by builder for ApprovalLog entities.
type ApprovalLogGroupBy struct {
	selector
	build *ApprovalLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *ApprovalLogGroupBy) Aggregate(fns ...AggregateFunc) *ApprovalLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *ApprovalLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, ent.OpQueryGroupBy)
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApprovalLogQuery, *ApprovalLogGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *ApprovalLogGroupBy) sqlScan(ctx context.Context, root *ApprovalLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApprovalLogSelect is the builder for selecting fields of ApprovalLog entities.
type ApprovalLogSelect struct {
	*ApprovalLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *ApprovalLogSelect) Aggregate(fns ...AggregateFunc) *ApprovalLogSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *ApprovalLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, ent.OpQuerySelect)
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApprovalLogQuery, *ApprovalLogSelect](ctx, als.ApprovalLogQuery, als, als.inters, v)
}

func (als *ApprovalLogSelect) sqlScan(ctx context.Context, root *ApprovalLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
