// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"itsm-backend/ent/cloudaccount"
	"itsm-backend/ent/cloudresource"
	"itsm-backend/ent/cloudservice"
	"itsm-backend/ent/configurationitem"
	"itsm-backend/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CloudResourceQuery is the builder for querying CloudResource entities.
type CloudResourceQuery struct {
	config
	ctx         *QueryContext
	order       []cloudresource.OrderOption
	inters      []Interceptor
	predicates  []predicate.CloudResource
	withAccount *CloudAccountQuery
	withService *CloudServiceQuery
	withCis     *ConfigurationItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CloudResourceQuery builder.
func (crq *CloudResourceQuery) Where(ps ...predicate.CloudResource) *CloudResourceQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CloudResourceQuery) Limit(limit int) *CloudResourceQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CloudResourceQuery) Offset(offset int) *CloudResourceQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CloudResourceQuery) Unique(unique bool) *CloudResourceQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CloudResourceQuery) Order(o ...cloudresource.OrderOption) *CloudResourceQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryAccount chains the current query on the "account" edge.
func (crq *CloudResourceQuery) QueryAccount() *CloudAccountQuery {
	query := (&CloudAccountClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cloudresource.Table, cloudresource.FieldID, selector),
			sqlgraph.To(cloudaccount.Table, cloudaccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cloudresource.AccountTable, cloudresource.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryService chains the current query on the "service" edge.
func (crq *CloudResourceQuery) QueryService() *CloudServiceQuery {
	query := (&CloudServiceClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cloudresource.Table, cloudresource.FieldID, selector),
			sqlgraph.To(cloudservice.Table, cloudservice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cloudresource.ServiceTable, cloudresource.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCis chains the current query on the "cis" edge.
func (crq *CloudResourceQuery) QueryCis() *ConfigurationItemQuery {
	query := (&ConfigurationItemClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cloudresource.Table, cloudresource.FieldID, selector),
			sqlgraph.To(configurationitem.Table, configurationitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, cloudresource.CisTable, cloudresource.CisColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CloudResource entity from the query.
// Returns a *NotFoundError when no CloudResource was found.
func (crq *CloudResourceQuery) First(ctx context.Context) (*CloudResource, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cloudresource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CloudResourceQuery) FirstX(ctx context.Context) *CloudResource {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CloudResource ID from the query.
// Returns a *NotFoundError when no CloudResource ID was found.
func (crq *CloudResourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cloudresource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CloudResourceQuery) FirstIDX(ctx context.Context) int {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CloudResource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CloudResource entity is found.
// Returns a *NotFoundError when no CloudResource entities are found.
func (crq *CloudResourceQuery) Only(ctx context.Context) (*CloudResource, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cloudresource.Label}
	default:
		return nil, &NotSingularError{cloudresource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CloudResourceQuery) OnlyX(ctx context.Context) *CloudResource {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CloudResource ID in the query.
// Returns a *NotSingularError when more than one CloudResource ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CloudResourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cloudresource.Label}
	default:
		err = &NotSingularError{cloudresource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CloudResourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CloudResources.
func (crq *CloudResourceQuery) All(ctx context.Context) ([]*CloudResource, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryAll)
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CloudResource, *CloudResourceQuery]()
	return withInterceptors[[]*CloudResource](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CloudResourceQuery) AllX(ctx context.Context) []*CloudResource {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CloudResource IDs.
func (crq *CloudResourceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryIDs)
	if err = crq.Select(cloudresource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CloudResourceQuery) IDsX(ctx context.Context) []int {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CloudResourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryCount)
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CloudResourceQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CloudResourceQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CloudResourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryExist)
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CloudResourceQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CloudResourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CloudResourceQuery) Clone() *CloudResourceQuery {
	if crq == nil {
		return nil
	}
	return &CloudResourceQuery{
		config:      crq.config,
		ctx:         crq.ctx.Clone(),
		order:       append([]cloudresource.OrderOption{}, crq.order...),
		inters:      append([]Interceptor{}, crq.inters...),
		predicates:  append([]predicate.CloudResource{}, crq.predicates...),
		withAccount: crq.withAccount.Clone(),
		withService: crq.withService.Clone(),
		withCis:     crq.withCis.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CloudResourceQuery) WithAccount(opts ...func(*CloudAccountQuery)) *CloudResourceQuery {
	query := (&CloudAccountClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withAccount = query
	return crq
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CloudResourceQuery) WithService(opts ...func(*CloudServiceQuery)) *CloudResourceQuery {
	query := (&CloudServiceClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withService = query
	return crq
}

// WithCis tells the query-builder to eager-load the nodes that are connected to
// the "cis" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CloudResourceQuery) WithCis(opts ...func(*ConfigurationItemQuery)) *CloudResourceQuery {
	query := (&ConfigurationItemClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withCis = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CloudAccountID int `json:"cloud_account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CloudResource.Query().
//		GroupBy(cloudresource.FieldCloudAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CloudResourceQuery) GroupBy(field string, fields ...string) *CloudResourceGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CloudResourceGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = cloudresource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CloudAccountID int `json:"cloud_account_id,omitempty"`
//	}
//
//	client.CloudResource.Query().
//		Select(cloudresource.FieldCloudAccountID).
//		Scan(ctx, &v)
func (crq *CloudResourceQuery) Select(fields ...string) *CloudResourceSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CloudResourceSelect{CloudResourceQuery: crq}
	sbuild.label = cloudresource.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CloudResourceSelect configured with the given aggregations.
func (crq *CloudResourceQuery) Aggregate(fns ...AggregateFunc) *CloudResourceSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CloudResourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !cloudresource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CloudResourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CloudResource, error) {
	var (
		nodes       = []*CloudResource{}
		_spec       = crq.querySpec()
		loadedTypes = [3]bool{
			crq.withAccount != nil,
			crq.withService != nil,
			crq.withCis != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CloudResource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CloudResource{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withAccount; query != nil {
		if err := crq.loadAccount(ctx, query, nodes, nil,
			func(n *CloudResource, e *CloudAccount) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withService; query != nil {
		if err := crq.loadService(ctx, query, nodes, nil,
			func(n *CloudResource, e *CloudService) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withCis; query != nil {
		if err := crq.loadCis(ctx, query, nodes,
			func(n *CloudResource) { n.Edges.Cis = []*ConfigurationItem{} },
			func(n *CloudResource, e *ConfigurationItem) { n.Edges.Cis = append(n.Edges.Cis, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CloudResourceQuery) loadAccount(ctx context.Context, query *CloudAccountQuery, nodes []*CloudResource, init func(*CloudResource), assign func(*CloudResource, *CloudAccount)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CloudResource)
	for i := range nodes {
		fk := nodes[i].CloudAccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cloudaccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cloud_account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CloudResourceQuery) loadService(ctx context.Context, query *CloudServiceQuery, nodes []*CloudResource, init func(*CloudResource), assign func(*CloudResource, *CloudService)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CloudResource)
	for i := range nodes {
		fk := nodes[i].ServiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cloudservice.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CloudResourceQuery) loadCis(ctx context.Context, query *ConfigurationItemQuery, nodes []*CloudResource, init func(*CloudResource), assign func(*CloudResource, *ConfigurationItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CloudResource)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(configurationitem.FieldCloudResourceRefID)
	}
	query.Where(predicate.ConfigurationItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(cloudresource.CisColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CloudResourceRefID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cloud_resource_ref_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (crq *CloudResourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CloudResourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cloudresource.Table, cloudresource.Columns, sqlgraph.NewFieldSpec(cloudresource.FieldID, field.TypeInt))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudresource.FieldID)
		for i := range fields {
			if fields[i] != cloudresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crq.withAccount != nil {
			_spec.Node.AddColumnOnce(cloudresource.FieldCloudAccountID)
		}
		if crq.withService != nil {
			_spec.Node.AddColumnOnce(cloudresource.FieldServiceID)
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CloudResourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(cloudresource.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = cloudresource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CloudResourceGroupBy is the group-by builder for CloudResource entities.
type CloudResourceGroupBy struct {
	selector
	build *CloudResourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CloudResourceGroupBy) Aggregate(fns ...AggregateFunc) *CloudResourceGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CloudResourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, ent.OpQueryGroupBy)
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudResourceQuery, *CloudResourceGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CloudResourceGroupBy) sqlScan(ctx context.Context, root *CloudResourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CloudResourceSelect is the builder for selecting fields of CloudResource entities.
type CloudResourceSelect struct {
	*CloudResourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CloudResourceSelect) Aggregate(fns ...AggregateFunc) *CloudResourceSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CloudResourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, ent.OpQuerySelect)
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudResourceQuery, *CloudResourceSelect](ctx, crs.CloudResourceQuery, crs, crs.inters, v)
}

func (crs *CloudResourceSelect) sqlScan(ctx context.Context, root *CloudResourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
