// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/processdefinition"
	"itsm-backend/ent/processdeployment"
	"itsm-backend/ent/processinstance"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProcessDefinitionUpdate is the builder for updating ProcessDefinition entities.
type ProcessDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessDefinitionMutation
}

// Where appends a list predicates to the ProcessDefinitionUpdate builder.
func (pdu *ProcessDefinitionUpdate) Where(ps ...predicate.ProcessDefinition) *ProcessDefinitionUpdate {
	pdu.mutation.Where(ps...)
	return pdu
}

// SetKey sets the "key" field.
func (pdu *ProcessDefinitionUpdate) SetKey(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetKey(s)
	return pdu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableKey(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetKey(*s)
	}
	return pdu
}

// SetName sets the "name" field.
func (pdu *ProcessDefinitionUpdate) SetName(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetName(s)
	return pdu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableName(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetName(*s)
	}
	return pdu
}

// SetDescription sets the "description" field.
func (pdu *ProcessDefinitionUpdate) SetDescription(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetDescription(s)
	return pdu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableDescription(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetDescription(*s)
	}
	return pdu
}

// ClearDescription clears the value of the "description" field.
func (pdu *ProcessDefinitionUpdate) ClearDescription() *ProcessDefinitionUpdate {
	pdu.mutation.ClearDescription()
	return pdu
}

// SetVersion sets the "version" field.
func (pdu *ProcessDefinitionUpdate) SetVersion(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetVersion(s)
	return pdu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableVersion(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetVersion(*s)
	}
	return pdu
}

// SetCategory sets the "category" field.
func (pdu *ProcessDefinitionUpdate) SetCategory(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetCategory(s)
	return pdu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableCategory(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetCategory(*s)
	}
	return pdu
}

// SetBpmnXML sets the "bpmn_xml" field.
func (pdu *ProcessDefinitionUpdate) SetBpmnXML(u []uint8) *ProcessDefinitionUpdate {
	pdu.mutation.SetBpmnXML(u)
	return pdu
}

// AppendBpmnXML appends u to the "bpmn_xml" field.
func (pdu *ProcessDefinitionUpdate) AppendBpmnXML(u []uint8) *ProcessDefinitionUpdate {
	pdu.mutation.AppendBpmnXML(u)
	return pdu
}

// SetProcessVariables sets the "process_variables" field.
func (pdu *ProcessDefinitionUpdate) SetProcessVariables(m map[string]interface{}) *ProcessDefinitionUpdate {
	pdu.mutation.SetProcessVariables(m)
	return pdu
}

// ClearProcessVariables clears the value of the "process_variables" field.
func (pdu *ProcessDefinitionUpdate) ClearProcessVariables() *ProcessDefinitionUpdate {
	pdu.mutation.ClearProcessVariables()
	return pdu
}

// SetIsActive sets the "is_active" field.
func (pdu *ProcessDefinitionUpdate) SetIsActive(b bool) *ProcessDefinitionUpdate {
	pdu.mutation.SetIsActive(b)
	return pdu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableIsActive(b *bool) *ProcessDefinitionUpdate {
	if b != nil {
		pdu.SetIsActive(*b)
	}
	return pdu
}

// SetIsLatest sets the "is_latest" field.
func (pdu *ProcessDefinitionUpdate) SetIsLatest(b bool) *ProcessDefinitionUpdate {
	pdu.mutation.SetIsLatest(b)
	return pdu
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableIsLatest(b *bool) *ProcessDefinitionUpdate {
	if b != nil {
		pdu.SetIsLatest(*b)
	}
	return pdu
}

// SetDeploymentID sets the "deployment_id" field.
func (pdu *ProcessDefinitionUpdate) SetDeploymentID(i int) *ProcessDefinitionUpdate {
	pdu.mutation.SetDeploymentID(i)
	return pdu
}

// SetNillableDeploymentID sets the "deployment_id" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableDeploymentID(i *int) *ProcessDefinitionUpdate {
	if i != nil {
		pdu.SetDeploymentID(*i)
	}
	return pdu
}

// SetDeploymentName sets the "deployment_name" field.
func (pdu *ProcessDefinitionUpdate) SetDeploymentName(s string) *ProcessDefinitionUpdate {
	pdu.mutation.SetDeploymentName(s)
	return pdu
}

// SetNillableDeploymentName sets the "deployment_name" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableDeploymentName(s *string) *ProcessDefinitionUpdate {
	if s != nil {
		pdu.SetDeploymentName(*s)
	}
	return pdu
}

// ClearDeploymentName clears the value of the "deployment_name" field.
func (pdu *ProcessDefinitionUpdate) ClearDeploymentName() *ProcessDefinitionUpdate {
	pdu.mutation.ClearDeploymentName()
	return pdu
}

// SetDeployedAt sets the "deployed_at" field.
func (pdu *ProcessDefinitionUpdate) SetDeployedAt(t time.Time) *ProcessDefinitionUpdate {
	pdu.mutation.SetDeployedAt(t)
	return pdu
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableDeployedAt(t *time.Time) *ProcessDefinitionUpdate {
	if t != nil {
		pdu.SetDeployedAt(*t)
	}
	return pdu
}

// SetTenantID sets the "tenant_id" field.
func (pdu *ProcessDefinitionUpdate) SetTenantID(i int) *ProcessDefinitionUpdate {
	pdu.mutation.ResetTenantID()
	pdu.mutation.SetTenantID(i)
	return pdu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableTenantID(i *int) *ProcessDefinitionUpdate {
	if i != nil {
		pdu.SetTenantID(*i)
	}
	return pdu
}

// AddTenantID adds i to the "tenant_id" field.
func (pdu *ProcessDefinitionUpdate) AddTenantID(i int) *ProcessDefinitionUpdate {
	pdu.mutation.AddTenantID(i)
	return pdu
}

// SetCreatedAt sets the "created_at" field.
func (pdu *ProcessDefinitionUpdate) SetCreatedAt(t time.Time) *ProcessDefinitionUpdate {
	pdu.mutation.SetCreatedAt(t)
	return pdu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pdu *ProcessDefinitionUpdate) SetNillableCreatedAt(t *time.Time) *ProcessDefinitionUpdate {
	if t != nil {
		pdu.SetCreatedAt(*t)
	}
	return pdu
}

// SetUpdatedAt sets the "updated_at" field.
func (pdu *ProcessDefinitionUpdate) SetUpdatedAt(t time.Time) *ProcessDefinitionUpdate {
	pdu.mutation.SetUpdatedAt(t)
	return pdu
}

// AddProcessInstanceIDs adds the "process_instances" edge to the ProcessInstance entity by IDs.
func (pdu *ProcessDefinitionUpdate) AddProcessInstanceIDs(ids ...int) *ProcessDefinitionUpdate {
	pdu.mutation.AddProcessInstanceIDs(ids...)
	return pdu
}

// AddProcessInstances adds the "process_instances" edges to the ProcessInstance entity.
func (pdu *ProcessDefinitionUpdate) AddProcessInstances(p ...*ProcessInstance) *ProcessDefinitionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pdu.AddProcessInstanceIDs(ids...)
}

// SetDeployment sets the "deployment" edge to the ProcessDeployment entity.
func (pdu *ProcessDefinitionUpdate) SetDeployment(p *ProcessDeployment) *ProcessDefinitionUpdate {
	return pdu.SetDeploymentID(p.ID)
}

// Mutation returns the ProcessDefinitionMutation object of the builder.
func (pdu *ProcessDefinitionUpdate) Mutation() *ProcessDefinitionMutation {
	return pdu.mutation
}

// ClearProcessInstances clears all "process_instances" edges to the ProcessInstance entity.
func (pdu *ProcessDefinitionUpdate) ClearProcessInstances() *ProcessDefinitionUpdate {
	pdu.mutation.ClearProcessInstances()
	return pdu
}

// RemoveProcessInstanceIDs removes the "process_instances" edge to ProcessInstance entities by IDs.
func (pdu *ProcessDefinitionUpdate) RemoveProcessInstanceIDs(ids ...int) *ProcessDefinitionUpdate {
	pdu.mutation.RemoveProcessInstanceIDs(ids...)
	return pdu
}

// RemoveProcessInstances removes "process_instances" edges to ProcessInstance entities.
func (pdu *ProcessDefinitionUpdate) RemoveProcessInstances(p ...*ProcessInstance) *ProcessDefinitionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pdu.RemoveProcessInstanceIDs(ids...)
}

// ClearDeployment clears the "deployment" edge to the ProcessDeployment entity.
func (pdu *ProcessDefinitionUpdate) ClearDeployment() *ProcessDefinitionUpdate {
	pdu.mutation.ClearDeployment()
	return pdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pdu *ProcessDefinitionUpdate) Save(ctx context.Context) (int, error) {
	pdu.defaults()
	return withHooks(ctx, pdu.sqlSave, pdu.mutation, pdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pdu *ProcessDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := pdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pdu *ProcessDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := pdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdu *ProcessDefinitionUpdate) ExecX(ctx context.Context) {
	if err := pdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pdu *ProcessDefinitionUpdate) defaults() {
	if _, ok := pdu.mutation.UpdatedAt(); !ok {
		v := processdefinition.UpdateDefaultUpdatedAt()
		pdu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pdu *ProcessDefinitionUpdate) check() error {
	if v, ok := pdu.mutation.Key(); ok {
		if err := processdefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.key": %w`, err)}
		}
	}
	if v, ok := pdu.mutation.Name(); ok {
		if err := processdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.name": %w`, err)}
		}
	}
	if v, ok := pdu.mutation.DeploymentID(); ok {
		if err := processdefinition.DeploymentIDValidator(v); err != nil {
			return &ValidationError{Name: "deployment_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.deployment_id": %w`, err)}
		}
	}
	if v, ok := pdu.mutation.TenantID(); ok {
		if err := processdefinition.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.tenant_id": %w`, err)}
		}
	}
	if pdu.mutation.DeploymentCleared() && len(pdu.mutation.DeploymentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProcessDefinition.deployment"`)
	}
	return nil
}

func (pdu *ProcessDefinitionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(processdefinition.Table, processdefinition.Columns, sqlgraph.NewFieldSpec(processdefinition.FieldID, field.TypeInt))
	if ps := pdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pdu.mutation.Key(); ok {
		_spec.SetField(processdefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := pdu.mutation.Name(); ok {
		_spec.SetField(processdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := pdu.mutation.Description(); ok {
		_spec.SetField(processdefinition.FieldDescription, field.TypeString, value)
	}
	if pdu.mutation.DescriptionCleared() {
		_spec.ClearField(processdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := pdu.mutation.Version(); ok {
		_spec.SetField(processdefinition.FieldVersion, field.TypeString, value)
	}
	if value, ok := pdu.mutation.Category(); ok {
		_spec.SetField(processdefinition.FieldCategory, field.TypeString, value)
	}
	if value, ok := pdu.mutation.BpmnXML(); ok {
		_spec.SetField(processdefinition.FieldBpmnXML, field.TypeJSON, value)
	}
	if value, ok := pdu.mutation.AppendedBpmnXML(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processdefinition.FieldBpmnXML, value)
		})
	}
	if value, ok := pdu.mutation.ProcessVariables(); ok {
		_spec.SetField(processdefinition.FieldProcessVariables, field.TypeJSON, value)
	}
	if pdu.mutation.ProcessVariablesCleared() {
		_spec.ClearField(processdefinition.FieldProcessVariables, field.TypeJSON)
	}
	if value, ok := pdu.mutation.IsActive(); ok {
		_spec.SetField(processdefinition.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := pdu.mutation.IsLatest(); ok {
		_spec.SetField(processdefinition.FieldIsLatest, field.TypeBool, value)
	}
	if value, ok := pdu.mutation.DeploymentName(); ok {
		_spec.SetField(processdefinition.FieldDeploymentName, field.TypeString, value)
	}
	if pdu.mutation.DeploymentNameCleared() {
		_spec.ClearField(processdefinition.FieldDeploymentName, field.TypeString)
	}
	if value, ok := pdu.mutation.DeployedAt(); ok {
		_spec.SetField(processdefinition.FieldDeployedAt, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.TenantID(); ok {
		_spec.SetField(processdefinition.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedTenantID(); ok {
		_spec.AddField(processdefinition.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.CreatedAt(); ok {
		_spec.SetField(processdefinition.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.UpdatedAt(); ok {
		_spec.SetField(processdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if pdu.mutation.ProcessInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.RemovedProcessInstancesIDs(); len(nodes) > 0 && !pdu.mutation.ProcessInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.ProcessInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pdu.mutation.DeploymentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   processdefinition.DeploymentTable,
			Columns: []string{processdefinition.DeploymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processdeployment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.DeploymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   processdefinition.DeploymentTable,
			Columns: []string{processdefinition.DeploymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processdeployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pdu.mutation.done = true
	return n, nil
}

// ProcessDefinitionUpdateOne is the builder for updating a single ProcessDefinition entity.
type ProcessDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessDefinitionMutation
}

// SetKey sets the "key" field.
func (pduo *ProcessDefinitionUpdateOne) SetKey(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetKey(s)
	return pduo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableKey(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetKey(*s)
	}
	return pduo
}

// SetName sets the "name" field.
func (pduo *ProcessDefinitionUpdateOne) SetName(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetName(s)
	return pduo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableName(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetName(*s)
	}
	return pduo
}

// SetDescription sets the "description" field.
func (pduo *ProcessDefinitionUpdateOne) SetDescription(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetDescription(s)
	return pduo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableDescription(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetDescription(*s)
	}
	return pduo
}

// ClearDescription clears the value of the "description" field.
func (pduo *ProcessDefinitionUpdateOne) ClearDescription() *ProcessDefinitionUpdateOne {
	pduo.mutation.ClearDescription()
	return pduo
}

// SetVersion sets the "version" field.
func (pduo *ProcessDefinitionUpdateOne) SetVersion(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetVersion(s)
	return pduo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableVersion(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetVersion(*s)
	}
	return pduo
}

// SetCategory sets the "category" field.
func (pduo *ProcessDefinitionUpdateOne) SetCategory(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetCategory(s)
	return pduo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableCategory(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetCategory(*s)
	}
	return pduo
}

// SetBpmnXML sets the "bpmn_xml" field.
func (pduo *ProcessDefinitionUpdateOne) SetBpmnXML(u []uint8) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetBpmnXML(u)
	return pduo
}

// AppendBpmnXML appends u to the "bpmn_xml" field.
func (pduo *ProcessDefinitionUpdateOne) AppendBpmnXML(u []uint8) *ProcessDefinitionUpdateOne {
	pduo.mutation.AppendBpmnXML(u)
	return pduo
}

// SetProcessVariables sets the "process_variables" field.
func (pduo *ProcessDefinitionUpdateOne) SetProcessVariables(m map[string]interface{}) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetProcessVariables(m)
	return pduo
}

// ClearProcessVariables clears the value of the "process_variables" field.
func (pduo *ProcessDefinitionUpdateOne) ClearProcessVariables() *ProcessDefinitionUpdateOne {
	pduo.mutation.ClearProcessVariables()
	return pduo
}

// SetIsActive sets the "is_active" field.
func (pduo *ProcessDefinitionUpdateOne) SetIsActive(b bool) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetIsActive(b)
	return pduo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableIsActive(b *bool) *ProcessDefinitionUpdateOne {
	if b != nil {
		pduo.SetIsActive(*b)
	}
	return pduo
}

// SetIsLatest sets the "is_latest" field.
func (pduo *ProcessDefinitionUpdateOne) SetIsLatest(b bool) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetIsLatest(b)
	return pduo
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableIsLatest(b *bool) *ProcessDefinitionUpdateOne {
	if b != nil {
		pduo.SetIsLatest(*b)
	}
	return pduo
}

// SetDeploymentID sets the "deployment_id" field.
func (pduo *ProcessDefinitionUpdateOne) SetDeploymentID(i int) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetDeploymentID(i)
	return pduo
}

// SetNillableDeploymentID sets the "deployment_id" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableDeploymentID(i *int) *ProcessDefinitionUpdateOne {
	if i != nil {
		pduo.SetDeploymentID(*i)
	}
	return pduo
}

// SetDeploymentName sets the "deployment_name" field.
func (pduo *ProcessDefinitionUpdateOne) SetDeploymentName(s string) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetDeploymentName(s)
	return pduo
}

// SetNillableDeploymentName sets the "deployment_name" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableDeploymentName(s *string) *ProcessDefinitionUpdateOne {
	if s != nil {
		pduo.SetDeploymentName(*s)
	}
	return pduo
}

// ClearDeploymentName clears the value of the "deployment_name" field.
func (pduo *ProcessDefinitionUpdateOne) ClearDeploymentName() *ProcessDefinitionUpdateOne {
	pduo.mutation.ClearDeploymentName()
	return pduo
}

// SetDeployedAt sets the "deployed_at" field.
func (pduo *ProcessDefinitionUpdateOne) SetDeployedAt(t time.Time) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetDeployedAt(t)
	return pduo
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableDeployedAt(t *time.Time) *ProcessDefinitionUpdateOne {
	if t != nil {
		pduo.SetDeployedAt(*t)
	}
	return pduo
}

// SetTenantID sets the "tenant_id" field.
func (pduo *ProcessDefinitionUpdateOne) SetTenantID(i int) *ProcessDefinitionUpdateOne {
	pduo.mutation.ResetTenantID()
	pduo.mutation.SetTenantID(i)
	return pduo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableTenantID(i *int) *ProcessDefinitionUpdateOne {
	if i != nil {
		pduo.SetTenantID(*i)
	}
	return pduo
}

// AddTenantID adds i to the "tenant_id" field.
func (pduo *ProcessDefinitionUpdateOne) AddTenantID(i int) *ProcessDefinitionUpdateOne {
	pduo.mutation.AddTenantID(i)
	return pduo
}

// SetCreatedAt sets the "created_at" field.
func (pduo *ProcessDefinitionUpdateOne) SetCreatedAt(t time.Time) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetCreatedAt(t)
	return pduo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pduo *ProcessDefinitionUpdateOne) SetNillableCreatedAt(t *time.Time) *ProcessDefinitionUpdateOne {
	if t != nil {
		pduo.SetCreatedAt(*t)
	}
	return pduo
}

// SetUpdatedAt sets the "updated_at" field.
func (pduo *ProcessDefinitionUpdateOne) SetUpdatedAt(t time.Time) *ProcessDefinitionUpdateOne {
	pduo.mutation.SetUpdatedAt(t)
	return pduo
}

// AddProcessInstanceIDs adds the "process_instances" edge to the ProcessInstance entity by IDs.
func (pduo *ProcessDefinitionUpdateOne) AddProcessInstanceIDs(ids ...int) *ProcessDefinitionUpdateOne {
	pduo.mutation.AddProcessInstanceIDs(ids...)
	return pduo
}

// AddProcessInstances adds the "process_instances" edges to the ProcessInstance entity.
func (pduo *ProcessDefinitionUpdateOne) AddProcessInstances(p ...*ProcessInstance) *ProcessDefinitionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pduo.AddProcessInstanceIDs(ids...)
}

// SetDeployment sets the "deployment" edge to the ProcessDeployment entity.
func (pduo *ProcessDefinitionUpdateOne) SetDeployment(p *ProcessDeployment) *ProcessDefinitionUpdateOne {
	return pduo.SetDeploymentID(p.ID)
}

// Mutation returns the ProcessDefinitionMutation object of the builder.
func (pduo *ProcessDefinitionUpdateOne) Mutation() *ProcessDefinitionMutation {
	return pduo.mutation
}

// ClearProcessInstances clears all "process_instances" edges to the ProcessInstance entity.
func (pduo *ProcessDefinitionUpdateOne) ClearProcessInstances() *ProcessDefinitionUpdateOne {
	pduo.mutation.ClearProcessInstances()
	return pduo
}

// RemoveProcessInstanceIDs removes the "process_instances" edge to ProcessInstance entities by IDs.
func (pduo *ProcessDefinitionUpdateOne) RemoveProcessInstanceIDs(ids ...int) *ProcessDefinitionUpdateOne {
	pduo.mutation.RemoveProcessInstanceIDs(ids...)
	return pduo
}

// RemoveProcessInstances removes "process_instances" edges to ProcessInstance entities.
func (pduo *ProcessDefinitionUpdateOne) RemoveProcessInstances(p ...*ProcessInstance) *ProcessDefinitionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pduo.RemoveProcessInstanceIDs(ids...)
}

// ClearDeployment clears the "deployment" edge to the ProcessDeployment entity.
func (pduo *ProcessDefinitionUpdateOne) ClearDeployment() *ProcessDefinitionUpdateOne {
	pduo.mutation.ClearDeployment()
	return pduo
}

// Where appends a list predicates to the ProcessDefinitionUpdate builder.
func (pduo *ProcessDefinitionUpdateOne) Where(ps ...predicate.ProcessDefinition) *ProcessDefinitionUpdateOne {
	pduo.mutation.Where(ps...)
	return pduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pduo *ProcessDefinitionUpdateOne) Select(field string, fields ...string) *ProcessDefinitionUpdateOne {
	pduo.fields = append([]string{field}, fields...)
	return pduo
}

// Save executes the query and returns the updated ProcessDefinition entity.
func (pduo *ProcessDefinitionUpdateOne) Save(ctx context.Context) (*ProcessDefinition, error) {
	pduo.defaults()
	return withHooks(ctx, pduo.sqlSave, pduo.mutation, pduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pduo *ProcessDefinitionUpdateOne) SaveX(ctx context.Context) *ProcessDefinition {
	node, err := pduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pduo *ProcessDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := pduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pduo *ProcessDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := pduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pduo *ProcessDefinitionUpdateOne) defaults() {
	if _, ok := pduo.mutation.UpdatedAt(); !ok {
		v := processdefinition.UpdateDefaultUpdatedAt()
		pduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pduo *ProcessDefinitionUpdateOne) check() error {
	if v, ok := pduo.mutation.Key(); ok {
		if err := processdefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.key": %w`, err)}
		}
	}
	if v, ok := pduo.mutation.Name(); ok {
		if err := processdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.name": %w`, err)}
		}
	}
	if v, ok := pduo.mutation.DeploymentID(); ok {
		if err := processdefinition.DeploymentIDValidator(v); err != nil {
			return &ValidationError{Name: "deployment_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.deployment_id": %w`, err)}
		}
	}
	if v, ok := pduo.mutation.TenantID(); ok {
		if err := processdefinition.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDefinition.tenant_id": %w`, err)}
		}
	}
	if pduo.mutation.DeploymentCleared() && len(pduo.mutation.DeploymentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProcessDefinition.deployment"`)
	}
	return nil
}

func (pduo *ProcessDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *ProcessDefinition, err error) {
	if err := pduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processdefinition.Table, processdefinition.Columns, sqlgraph.NewFieldSpec(processdefinition.FieldID, field.TypeInt))
	id, ok := pduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processdefinition.FieldID)
		for _, f := range fields {
			if !processdefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pduo.mutation.Key(); ok {
		_spec.SetField(processdefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := pduo.mutation.Name(); ok {
		_spec.SetField(processdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := pduo.mutation.Description(); ok {
		_spec.SetField(processdefinition.FieldDescription, field.TypeString, value)
	}
	if pduo.mutation.DescriptionCleared() {
		_spec.ClearField(processdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := pduo.mutation.Version(); ok {
		_spec.SetField(processdefinition.FieldVersion, field.TypeString, value)
	}
	if value, ok := pduo.mutation.Category(); ok {
		_spec.SetField(processdefinition.FieldCategory, field.TypeString, value)
	}
	if value, ok := pduo.mutation.BpmnXML(); ok {
		_spec.SetField(processdefinition.FieldBpmnXML, field.TypeJSON, value)
	}
	if value, ok := pduo.mutation.AppendedBpmnXML(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processdefinition.FieldBpmnXML, value)
		})
	}
	if value, ok := pduo.mutation.ProcessVariables(); ok {
		_spec.SetField(processdefinition.FieldProcessVariables, field.TypeJSON, value)
	}
	if pduo.mutation.ProcessVariablesCleared() {
		_spec.ClearField(processdefinition.FieldProcessVariables, field.TypeJSON)
	}
	if value, ok := pduo.mutation.IsActive(); ok {
		_spec.SetField(processdefinition.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := pduo.mutation.IsLatest(); ok {
		_spec.SetField(processdefinition.FieldIsLatest, field.TypeBool, value)
	}
	if value, ok := pduo.mutation.DeploymentName(); ok {
		_spec.SetField(processdefinition.FieldDeploymentName, field.TypeString, value)
	}
	if pduo.mutation.DeploymentNameCleared() {
		_spec.ClearField(processdefinition.FieldDeploymentName, field.TypeString)
	}
	if value, ok := pduo.mutation.DeployedAt(); ok {
		_spec.SetField(processdefinition.FieldDeployedAt, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.TenantID(); ok {
		_spec.SetField(processdefinition.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedTenantID(); ok {
		_spec.AddField(processdefinition.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.CreatedAt(); ok {
		_spec.SetField(processdefinition.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.UpdatedAt(); ok {
		_spec.SetField(processdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if pduo.mutation.ProcessInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.RemovedProcessInstancesIDs(); len(nodes) > 0 && !pduo.mutation.ProcessInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.ProcessInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdefinition.ProcessInstancesTable,
			Columns: []string{processdefinition.ProcessInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pduo.mutation.DeploymentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   processdefinition.DeploymentTable,
			Columns: []string{processdefinition.DeploymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processdeployment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.DeploymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   processdefinition.DeploymentTable,
			Columns: []string{processdefinition.DeploymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processdeployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProcessDefinition{config: pduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pduo.mutation.done = true
	return _node, nil
}
