// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/prompttemplate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PromptTemplateCreate is the builder for creating a PromptTemplate entity.
type PromptTemplateCreate struct {
	config
	mutation *PromptTemplateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptTemplateCreate) SetCreatedAt(v time.Time) *PromptTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptTemplateCreate) SetNillableCreatedAt(v *time.Time) *PromptTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptTemplateCreate) SetUpdatedAt(v time.Time) *PromptTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptTemplateCreate) SetNillableUpdatedAt(v *time.Time) *PromptTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PromptTemplateCreate) SetName(v string) *PromptTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PromptTemplateCreate) SetVersion(v string) *PromptTemplateCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *PromptTemplateCreate) SetNillableVersion(v *string) *PromptTemplateCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetTemplate sets the "template" field.
func (_c *PromptTemplateCreate) SetTemplate(v string) *PromptTemplateCreate {
	_c.mutation.SetTemplate(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromptTemplateCreate) SetDescription(v string) *PromptTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromptTemplateCreate) SetNillableDescription(v *string) *PromptTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PromptTemplateCreate) SetMetadata(v map[string]interface{}) *PromptTemplateCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// Mutation returns the PromptTemplateMutation object of the builder.
func (_c *PromptTemplateCreate) Mutation() *PromptTemplateMutation {
	return _c.mutation
}

// Save creates the PromptTemplate in the database.
func (_c *PromptTemplateCreate) Save(ctx context.Context) (*PromptTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptTemplateCreate) SaveX(ctx context.Context) *PromptTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prompttemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prompttemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := prompttemplate.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := prompttemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromptTemplate.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromptTemplate.name"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PromptTemplate.version"`)}
	}
	if _, ok := _c.mutation.Template(); !ok {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required field "PromptTemplate.template"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "PromptTemplate.description"`)}
	}
	return nil
}

func (_c *PromptTemplateCreate) sqlSave(ctx context.Context) (*PromptTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptTemplateCreate) createSpec() (*PromptTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prompttemplate.Table, sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prompttemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(prompttemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(prompttemplate.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Template(); ok {
		_spec.SetField(prompttemplate.FieldTemplate, field.TypeString, value)
		_node.Template = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(prompttemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(prompttemplate.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// PromptTemplateCreateBulk is the builder for creating many PromptTemplate entities in bulk.
type PromptTemplateCreateBulk struct {
	config
	err      error
	builders []*PromptTemplateCreate
}

// Save creates the PromptTemplate entities in the database.
func (_c *PromptTemplateCreateBulk) Save(ctx context.Context) ([]*PromptTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptTemplateCreateBulk) SaveX(ctx context.Context) []*PromptTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
