// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/servicecatalog"
	"itsm-backend/ent/servicecatalogitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceCatalogItemUpdate is the builder for updating ServiceCatalogItem entities.
type ServiceCatalogItemUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceCatalogItemMutation
}

// Where appends a list predicates to the ServiceCatalogItemUpdate builder.
func (_u *ServiceCatalogItemUpdate) Where(ps ...predicate.ServiceCatalogItem) *ServiceCatalogItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCatalogID sets the "catalog_id" field.
func (_u *ServiceCatalogItemUpdate) SetCatalogID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.SetCatalogID(v)
	return _u
}

// SetNillableCatalogID sets the "catalog_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableCatalogID(v *int) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetCatalogID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceCatalogItemUpdate) SetName(v string) *ServiceCatalogItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableName(v *string) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceCatalogItemUpdate) SetDescription(v string) *ServiceCatalogItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableDescription(v *string) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceCatalogItemUpdate) ClearDescription() *ServiceCatalogItemUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDetails sets the "details" field.
func (_u *ServiceCatalogItemUpdate) SetDetails(v string) *ServiceCatalogItemUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableDetails(v *string) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ServiceCatalogItemUpdate) ClearDetails() *ServiceCatalogItemUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ServiceCatalogItemUpdate) SetCategory(v string) *ServiceCatalogItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableCategory(v *string) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ServiceCatalogItemUpdate) ClearCategory() *ServiceCatalogItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ServiceCatalogItemUpdate) SetIcon(v string) *ServiceCatalogItemUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableIcon(v *string) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ServiceCatalogItemUpdate) ClearIcon() *ServiceCatalogItemUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetFormSchema sets the "form_schema" field.
func (_u *ServiceCatalogItemUpdate) SetFormSchema(v map[string]interface{}) *ServiceCatalogItemUpdate {
	_u.mutation.SetFormSchema(v)
	return _u
}

// ClearFormSchema clears the value of the "form_schema" field.
func (_u *ServiceCatalogItemUpdate) ClearFormSchema() *ServiceCatalogItemUpdate {
	_u.mutation.ClearFormSchema()
	return _u
}

// SetSLAID sets the "sla_id" field.
func (_u *ServiceCatalogItemUpdate) SetSLAID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.ResetSLAID()
	_u.mutation.SetSLAID(v)
	return _u
}

// SetNillableSLAID sets the "sla_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableSLAID(v *int) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetSLAID(*v)
	}
	return _u
}

// AddSLAID adds value to the "sla_id" field.
func (_u *ServiceCatalogItemUpdate) AddSLAID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.AddSLAID(v)
	return _u
}

// ClearSLAID clears the value of the "sla_id" field.
func (_u *ServiceCatalogItemUpdate) ClearSLAID() *ServiceCatalogItemUpdate {
	_u.mutation.ClearSLAID()
	return _u
}

// SetApprovalChainID sets the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdate) SetApprovalChainID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.ResetApprovalChainID()
	_u.mutation.SetApprovalChainID(v)
	return _u
}

// SetNillableApprovalChainID sets the "approval_chain_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableApprovalChainID(v *int) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetApprovalChainID(*v)
	}
	return _u
}

// AddApprovalChainID adds value to the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdate) AddApprovalChainID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.AddApprovalChainID(v)
	return _u
}

// ClearApprovalChainID clears the value of the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdate) ClearApprovalChainID() *ServiceCatalogItemUpdate {
	_u.mutation.ClearApprovalChainID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceCatalogItemUpdate) SetIsActive(v bool) *ServiceCatalogItemUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableIsActive(v *bool) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRequiresApproval sets the "requires_approval" field.
func (_u *ServiceCatalogItemUpdate) SetRequiresApproval(v bool) *ServiceCatalogItemUpdate {
	_u.mutation.SetRequiresApproval(v)
	return _u
}

// SetNillableRequiresApproval sets the "requires_approval" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableRequiresApproval(v *bool) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetRequiresApproval(*v)
	}
	return _u
}

// SetEstimatedDays sets the "estimated_days" field.
func (_u *ServiceCatalogItemUpdate) SetEstimatedDays(v int) *ServiceCatalogItemUpdate {
	_u.mutation.ResetEstimatedDays()
	_u.mutation.SetEstimatedDays(v)
	return _u
}

// SetNillableEstimatedDays sets the "estimated_days" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableEstimatedDays(v *int) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetEstimatedDays(*v)
	}
	return _u
}

// AddEstimatedDays adds value to the "estimated_days" field.
func (_u *ServiceCatalogItemUpdate) AddEstimatedDays(v int) *ServiceCatalogItemUpdate {
	_u.mutation.AddEstimatedDays(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ServiceCatalogItemUpdate) SetTenantID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableTenantID(v *int) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ServiceCatalogItemUpdate) AddTenantID(v int) *ServiceCatalogItemUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServiceCatalogItemUpdate) SetCreatedAt(v time.Time) *ServiceCatalogItemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdate) SetNillableCreatedAt(v *time.Time) *ServiceCatalogItemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceCatalogItemUpdate) SetUpdatedAt(v time.Time) *ServiceCatalogItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCatalog sets the "catalog" edge to the ServiceCatalog entity.
func (_u *ServiceCatalogItemUpdate) SetCatalog(v *ServiceCatalog) *ServiceCatalogItemUpdate {
	return _u.SetCatalogID(v.ID)
}

// Mutation returns the ServiceCatalogItemMutation object of the builder.
func (_u *ServiceCatalogItemUpdate) Mutation() *ServiceCatalogItemMutation {
	return _u.mutation
}

// ClearCatalog clears the "catalog" edge to the ServiceCatalog entity.
func (_u *ServiceCatalogItemUpdate) ClearCatalog() *ServiceCatalogItemUpdate {
	_u.mutation.ClearCatalog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceCatalogItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceCatalogItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceCatalogItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceCatalogItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceCatalogItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicecatalogitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceCatalogItemUpdate) check() error {
	if v, ok := _u.mutation.CatalogID(); ok {
		if err := servicecatalogitem.CatalogIDValidator(v); err != nil {
			return &ValidationError{Name: "catalog_id", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.catalog_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := servicecatalogitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := servicecatalogitem.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.tenant_id": %w`, err)}
		}
	}
	if _u.mutation.CatalogCleared() && len(_u.mutation.CatalogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCatalogItem.catalog"`)
	}
	return nil
}

func (_u *ServiceCatalogItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecatalogitem.Table, servicecatalogitem.Columns, sqlgraph.NewFieldSpec(servicecatalogitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servicecatalogitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(servicecatalogitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(servicecatalogitem.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(servicecatalogitem.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(servicecatalogitem.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(servicecatalogitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(servicecatalogitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(servicecatalogitem.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(servicecatalogitem.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.FormSchema(); ok {
		_spec.SetField(servicecatalogitem.FieldFormSchema, field.TypeJSON, value)
	}
	if _u.mutation.FormSchemaCleared() {
		_spec.ClearField(servicecatalogitem.FieldFormSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.SLAID(); ok {
		_spec.SetField(servicecatalogitem.FieldSLAID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSLAID(); ok {
		_spec.AddField(servicecatalogitem.FieldSLAID, field.TypeInt, value)
	}
	if _u.mutation.SLAIDCleared() {
		_spec.ClearField(servicecatalogitem.FieldSLAID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApprovalChainID(); ok {
		_spec.SetField(servicecatalogitem.FieldApprovalChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedApprovalChainID(); ok {
		_spec.AddField(servicecatalogitem.FieldApprovalChainID, field.TypeInt, value)
	}
	if _u.mutation.ApprovalChainIDCleared() {
		_spec.ClearField(servicecatalogitem.FieldApprovalChainID, field.TypeInt)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(servicecatalogitem.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresApproval(); ok {
		_spec.SetField(servicecatalogitem.FieldRequiresApproval, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EstimatedDays(); ok {
		_spec.SetField(servicecatalogitem.FieldEstimatedDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedDays(); ok {
		_spec.AddField(servicecatalogitem.FieldEstimatedDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(servicecatalogitem.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(servicecatalogitem.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(servicecatalogitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicecatalogitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CatalogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servicecatalogitem.CatalogTable,
			Columns: []string{servicecatalogitem.CatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicecatalog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CatalogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servicecatalogitem.CatalogTable,
			Columns: []string{servicecatalogitem.CatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicecatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecatalogitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceCatalogItemUpdateOne is the builder for updating a single ServiceCatalogItem entity.
type ServiceCatalogItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceCatalogItemMutation
}

// SetCatalogID sets the "catalog_id" field.
func (_u *ServiceCatalogItemUpdateOne) SetCatalogID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetCatalogID(v)
	return _u
}

// SetNillableCatalogID sets the "catalog_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableCatalogID(v *int) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetCatalogID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceCatalogItemUpdateOne) SetName(v string) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableName(v *string) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceCatalogItemUpdateOne) SetDescription(v string) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableDescription(v *string) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceCatalogItemUpdateOne) ClearDescription() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDetails sets the "details" field.
func (_u *ServiceCatalogItemUpdateOne) SetDetails(v string) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableDetails(v *string) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ServiceCatalogItemUpdateOne) ClearDetails() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ServiceCatalogItemUpdateOne) SetCategory(v string) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableCategory(v *string) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ServiceCatalogItemUpdateOne) ClearCategory() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ServiceCatalogItemUpdateOne) SetIcon(v string) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableIcon(v *string) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ServiceCatalogItemUpdateOne) ClearIcon() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetFormSchema sets the "form_schema" field.
func (_u *ServiceCatalogItemUpdateOne) SetFormSchema(v map[string]interface{}) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetFormSchema(v)
	return _u
}

// ClearFormSchema clears the value of the "form_schema" field.
func (_u *ServiceCatalogItemUpdateOne) ClearFormSchema() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearFormSchema()
	return _u
}

// SetSLAID sets the "sla_id" field.
func (_u *ServiceCatalogItemUpdateOne) SetSLAID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.ResetSLAID()
	_u.mutation.SetSLAID(v)
	return _u
}

// SetNillableSLAID sets the "sla_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableSLAID(v *int) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetSLAID(*v)
	}
	return _u
}

// AddSLAID adds value to the "sla_id" field.
func (_u *ServiceCatalogItemUpdateOne) AddSLAID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.AddSLAID(v)
	return _u
}

// ClearSLAID clears the value of the "sla_id" field.
func (_u *ServiceCatalogItemUpdateOne) ClearSLAID() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearSLAID()
	return _u
}

// SetApprovalChainID sets the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdateOne) SetApprovalChainID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.ResetApprovalChainID()
	_u.mutation.SetApprovalChainID(v)
	return _u
}

// SetNillableApprovalChainID sets the "approval_chain_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableApprovalChainID(v *int) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetApprovalChainID(*v)
	}
	return _u
}

// AddApprovalChainID adds value to the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdateOne) AddApprovalChainID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.AddApprovalChainID(v)
	return _u
}

// ClearApprovalChainID clears the value of the "approval_chain_id" field.
func (_u *ServiceCatalogItemUpdateOne) ClearApprovalChainID() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearApprovalChainID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceCatalogItemUpdateOne) SetIsActive(v bool) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableIsActive(v *bool) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRequiresApproval sets the "requires_approval" field.
func (_u *ServiceCatalogItemUpdateOne) SetRequiresApproval(v bool) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetRequiresApproval(v)
	return _u
}

// SetNillableRequiresApproval sets the "requires_approval" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableRequiresApproval(v *bool) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetRequiresApproval(*v)
	}
	return _u
}

// SetEstimatedDays sets the "estimated_days" field.
func (_u *ServiceCatalogItemUpdateOne) SetEstimatedDays(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.ResetEstimatedDays()
	_u.mutation.SetEstimatedDays(v)
	return _u
}

// SetNillableEstimatedDays sets the "estimated_days" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableEstimatedDays(v *int) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetEstimatedDays(*v)
	}
	return _u
}

// AddEstimatedDays adds value to the "estimated_days" field.
func (_u *ServiceCatalogItemUpdateOne) AddEstimatedDays(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.AddEstimatedDays(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ServiceCatalogItemUpdateOne) SetTenantID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableTenantID(v *int) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ServiceCatalogItemUpdateOne) AddTenantID(v int) *ServiceCatalogItemUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServiceCatalogItemUpdateOne) SetCreatedAt(v time.Time) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServiceCatalogItemUpdateOne) SetNillableCreatedAt(v *time.Time) *ServiceCatalogItemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceCatalogItemUpdateOne) SetUpdatedAt(v time.Time) *ServiceCatalogItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCatalog sets the "catalog" edge to the ServiceCatalog entity.
func (_u *ServiceCatalogItemUpdateOne) SetCatalog(v *ServiceCatalog) *ServiceCatalogItemUpdateOne {
	return _u.SetCatalogID(v.ID)
}

// Mutation returns the ServiceCatalogItemMutation object of the builder.
func (_u *ServiceCatalogItemUpdateOne) Mutation() *ServiceCatalogItemMutation {
	return _u.mutation
}

// ClearCatalog clears the "catalog" edge to the ServiceCatalog entity.
func (_u *ServiceCatalogItemUpdateOne) ClearCatalog() *ServiceCatalogItemUpdateOne {
	_u.mutation.ClearCatalog()
	return _u
}

// Where appends a list predicates to the ServiceCatalogItemUpdate builder.
func (_u *ServiceCatalogItemUpdateOne) Where(ps ...predicate.ServiceCatalogItem) *ServiceCatalogItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceCatalogItemUpdateOne) Select(field string, fields ...string) *ServiceCatalogItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceCatalogItem entity.
func (_u *ServiceCatalogItemUpdateOne) Save(ctx context.Context) (*ServiceCatalogItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceCatalogItemUpdateOne) SaveX(ctx context.Context) *ServiceCatalogItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceCatalogItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceCatalogItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceCatalogItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicecatalogitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceCatalogItemUpdateOne) check() error {
	if v, ok := _u.mutation.CatalogID(); ok {
		if err := servicecatalogitem.CatalogIDValidator(v); err != nil {
			return &ValidationError{Name: "catalog_id", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.catalog_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := servicecatalogitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := servicecatalogitem.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ServiceCatalogItem.tenant_id": %w`, err)}
		}
	}
	if _u.mutation.CatalogCleared() && len(_u.mutation.CatalogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceCatalogItem.catalog"`)
	}
	return nil
}

func (_u *ServiceCatalogItemUpdateOne) sqlSave(ctx context.Context) (_node *ServiceCatalogItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecatalogitem.Table, servicecatalogitem.Columns, sqlgraph.NewFieldSpec(servicecatalogitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceCatalogItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicecatalogitem.FieldID)
		for _, f := range fields {
			if !servicecatalogitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servicecatalogitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servicecatalogitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(servicecatalogitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(servicecatalogitem.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(servicecatalogitem.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(servicecatalogitem.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(servicecatalogitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(servicecatalogitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(servicecatalogitem.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(servicecatalogitem.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.FormSchema(); ok {
		_spec.SetField(servicecatalogitem.FieldFormSchema, field.TypeJSON, value)
	}
	if _u.mutation.FormSchemaCleared() {
		_spec.ClearField(servicecatalogitem.FieldFormSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.SLAID(); ok {
		_spec.SetField(servicecatalogitem.FieldSLAID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSLAID(); ok {
		_spec.AddField(servicecatalogitem.FieldSLAID, field.TypeInt, value)
	}
	if _u.mutation.SLAIDCleared() {
		_spec.ClearField(servicecatalogitem.FieldSLAID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApprovalChainID(); ok {
		_spec.SetField(servicecatalogitem.FieldApprovalChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedApprovalChainID(); ok {
		_spec.AddField(servicecatalogitem.FieldApprovalChainID, field.TypeInt, value)
	}
	if _u.mutation.ApprovalChainIDCleared() {
		_spec.ClearField(servicecatalogitem.FieldApprovalChainID, field.TypeInt)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(servicecatalogitem.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresApproval(); ok {
		_spec.SetField(servicecatalogitem.FieldRequiresApproval, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EstimatedDays(); ok {
		_spec.SetField(servicecatalogitem.FieldEstimatedDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedDays(); ok {
		_spec.AddField(servicecatalogitem.FieldEstimatedDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(servicecatalogitem.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(servicecatalogitem.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(servicecatalogitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicecatalogitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CatalogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servicecatalogitem.CatalogTable,
			Columns: []string{servicecatalogitem.CatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicecatalog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CatalogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servicecatalogitem.CatalogTable,
			Columns: []string{servicecatalogitem.CatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicecatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServiceCatalogItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecatalogitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
