// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/sladefinition"
	"itsm-backend/ent/slaviolation"
	"itsm-backend/ent/ticket"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SLAViolationQuery is the builder for querying SLAViolation entities.
type SLAViolationQuery struct {
	config
	ctx               *QueryContext
	order             []slaviolation.OrderOption
	inters            []Interceptor
	predicates        []predicate.SLAViolation
	withSLADefinition *SLADefinitionQuery
	withTicket        *TicketQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SLAViolationQuery builder.
func (_q *SLAViolationQuery) Where(ps ...predicate.SLAViolation) *SLAViolationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SLAViolationQuery) Limit(limit int) *SLAViolationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SLAViolationQuery) Offset(offset int) *SLAViolationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SLAViolationQuery) Unique(unique bool) *SLAViolationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SLAViolationQuery) Order(o ...slaviolation.OrderOption) *SLAViolationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySLADefinition chains the current query on the "sla_definition" edge.
func (_q *SLAViolationQuery) QuerySLADefinition() *SLADefinitionQuery {
	query := (&SLADefinitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(slaviolation.Table, slaviolation.FieldID, selector),
			sqlgraph.To(sladefinition.Table, sladefinition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, slaviolation.SLADefinitionTable, slaviolation.SLADefinitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTicket chains the current query on the "ticket" edge.
func (_q *SLAViolationQuery) QueryTicket() *TicketQuery {
	query := (&TicketClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(slaviolation.Table, slaviolation.FieldID, selector),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, slaviolation.TicketTable, slaviolation.TicketColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SLAViolation entity from the query.
// Returns a *NotFoundError when no SLAViolation was found.
func (_q *SLAViolationQuery) First(ctx context.Context) (*SLAViolation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{slaviolation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SLAViolationQuery) FirstX(ctx context.Context) *SLAViolation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SLAViolation ID from the query.
// Returns a *NotFoundError when no SLAViolation ID was found.
func (_q *SLAViolationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{slaviolation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SLAViolationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SLAViolation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SLAViolation entity is found.
// Returns a *NotFoundError when no SLAViolation entities are found.
func (_q *SLAViolationQuery) Only(ctx context.Context) (*SLAViolation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{slaviolation.Label}
	default:
		return nil, &NotSingularError{slaviolation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SLAViolationQuery) OnlyX(ctx context.Context) *SLAViolation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SLAViolation ID in the query.
// Returns a *NotSingularError when more than one SLAViolation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SLAViolationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{slaviolation.Label}
	default:
		err = &NotSingularError{slaviolation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SLAViolationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SLAViolations.
func (_q *SLAViolationQuery) All(ctx context.Context) ([]*SLAViolation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SLAViolation, *SLAViolationQuery]()
	return withInterceptors[[]*SLAViolation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SLAViolationQuery) AllX(ctx context.Context) []*SLAViolation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SLAViolation IDs.
func (_q *SLAViolationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(slaviolation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SLAViolationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SLAViolationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SLAViolationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SLAViolationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SLAViolationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SLAViolationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SLAViolationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SLAViolationQuery) Clone() *SLAViolationQuery {
	if _q == nil {
		return nil
	}
	return &SLAViolationQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]slaviolation.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.SLAViolation{}, _q.predicates...),
		withSLADefinition: _q.withSLADefinition.Clone(),
		withTicket:        _q.withTicket.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSLADefinition tells the query-builder to eager-load the nodes that are connected to
// the "sla_definition" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SLAViolationQuery) WithSLADefinition(opts ...func(*SLADefinitionQuery)) *SLAViolationQuery {
	query := (&SLADefinitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSLADefinition = query
	return _q
}

// WithTicket tells the query-builder to eager-load the nodes that are connected to
// the "ticket" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SLAViolationQuery) WithTicket(opts ...func(*TicketQuery)) *SLAViolationQuery {
	query := (&TicketClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTicket = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SLAViolation.Query().
//		GroupBy(slaviolation.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SLAViolationQuery) GroupBy(field string, fields ...string) *SLAViolationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SLAViolationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = slaviolation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//	}
//
//	client.SLAViolation.Query().
//		Select(slaviolation.FieldCreatedBy).
//		Scan(ctx, &v)
func (_q *SLAViolationQuery) Select(fields ...string) *SLAViolationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SLAViolationSelect{SLAViolationQuery: _q}
	sbuild.label = slaviolation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SLAViolationSelect configured with the given aggregations.
func (_q *SLAViolationQuery) Aggregate(fns ...AggregateFunc) *SLAViolationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SLAViolationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !slaviolation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SLAViolationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SLAViolation, error) {
	var (
		nodes       = []*SLAViolation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSLADefinition != nil,
			_q.withTicket != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SLAViolation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SLAViolation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSLADefinition; query != nil {
		if err := _q.loadSLADefinition(ctx, query, nodes, nil,
			func(n *SLAViolation, e *SLADefinition) { n.Edges.SLADefinition = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTicket; query != nil {
		if err := _q.loadTicket(ctx, query, nodes, nil,
			func(n *SLAViolation, e *Ticket) { n.Edges.Ticket = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SLAViolationQuery) loadSLADefinition(ctx context.Context, query *SLADefinitionQuery, nodes []*SLAViolation, init func(*SLAViolation), assign func(*SLAViolation, *SLADefinition)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SLAViolation)
	for i := range nodes {
		fk := nodes[i].SLADefinitionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sladefinition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sla_definition_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SLAViolationQuery) loadTicket(ctx context.Context, query *TicketQuery, nodes []*SLAViolation, init func(*SLAViolation), assign func(*SLAViolation, *Ticket)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SLAViolation)
	for i := range nodes {
		fk := nodes[i].TicketID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ticket.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ticket_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SLAViolationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SLAViolationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(slaviolation.Table, slaviolation.Columns, sqlgraph.NewFieldSpec(slaviolation.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, slaviolation.FieldID)
		for i := range fields {
			if fields[i] != slaviolation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSLADefinition != nil {
			_spec.Node.AddColumnOnce(slaviolation.FieldSLADefinitionID)
		}
		if _q.withTicket != nil {
			_spec.Node.AddColumnOnce(slaviolation.FieldTicketID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SLAViolationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(slaviolation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = slaviolation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SLAViolationGroupBy is the group-by builder for SLAViolation entities.
type SLAViolationGroupBy struct {
	selector
	build *SLAViolationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SLAViolationGroupBy) Aggregate(fns ...AggregateFunc) *SLAViolationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SLAViolationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SLAViolationQuery, *SLAViolationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SLAViolationGroupBy) sqlScan(ctx context.Context, root *SLAViolationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SLAViolationSelect is the builder for selecting fields of SLAViolation entities.
type SLAViolationSelect struct {
	*SLAViolationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SLAViolationSelect) Aggregate(fns ...AggregateFunc) *SLAViolationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SLAViolationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SLAViolationQuery, *SLAViolationSelect](ctx, _s.SLAViolationQuery, _s, _s.inters, v)
}

func (_s *SLAViolationSelect) sqlScan(ctx context.Context, root *SLAViolationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
