// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/emailconversation"
	"itsm-backend/ent/externalcontractreference"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/sourceorganization"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SourceOrganizationUpdate is the builder for updating SourceOrganization entities.
type SourceOrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *SourceOrganizationMutation
}

// Where appends a list predicates to the SourceOrganizationUpdate builder.
func (_u *SourceOrganizationUpdate) Where(ps ...predicate.SourceOrganization) *SourceOrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *SourceOrganizationUpdate) SetTenantID(v int) *SourceOrganizationUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SourceOrganizationUpdate) SetNillableTenantID(v *int) *SourceOrganizationUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *SourceOrganizationUpdate) AddTenantID(v int) *SourceOrganizationUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SourceOrganizationUpdate) SetName(v string) *SourceOrganizationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SourceOrganizationUpdate) SetNillableName(v *string) *SourceOrganizationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *SourceOrganizationUpdate) SetNormalizedName(v string) *SourceOrganizationUpdate {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *SourceOrganizationUpdate) SetNillableNormalizedName(v *string) *SourceOrganizationUpdate {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetEmailAddresses sets the "email_addresses" field.
func (_u *SourceOrganizationUpdate) SetEmailAddresses(v []string) *SourceOrganizationUpdate {
	_u.mutation.SetEmailAddresses(v)
	return _u
}

// AppendEmailAddresses appends value to the "email_addresses" field.
func (_u *SourceOrganizationUpdate) AppendEmailAddresses(v []string) *SourceOrganizationUpdate {
	_u.mutation.AppendEmailAddresses(v)
	return _u
}

// ClearEmailAddresses clears the value of the "email_addresses" field.
func (_u *SourceOrganizationUpdate) ClearEmailAddresses() *SourceOrganizationUpdate {
	_u.mutation.ClearEmailAddresses()
	return _u
}

// SetEmailDomains sets the "email_domains" field.
func (_u *SourceOrganizationUpdate) SetEmailDomains(v []string) *SourceOrganizationUpdate {
	_u.mutation.SetEmailDomains(v)
	return _u
}

// AppendEmailDomains appends value to the "email_domains" field.
func (_u *SourceOrganizationUpdate) AppendEmailDomains(v []string) *SourceOrganizationUpdate {
	_u.mutation.AppendEmailDomains(v)
	return _u
}

// ClearEmailDomains clears the value of the "email_domains" field.
func (_u *SourceOrganizationUpdate) ClearEmailDomains() *SourceOrganizationUpdate {
	_u.mutation.ClearEmailDomains()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceOrganizationUpdate) SetStatus(v string) *SourceOrganizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceOrganizationUpdate) SetNillableStatus(v *string) *SourceOrganizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SourceOrganizationUpdate) SetCreatedAt(v time.Time) *SourceOrganizationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SourceOrganizationUpdate) SetNillableCreatedAt(v *time.Time) *SourceOrganizationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceOrganizationUpdate) SetUpdatedAt(v time.Time) *SourceOrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddExternalContractReferenceIDs adds the "external_contract_references" edge to the ExternalContractReference entity by IDs.
func (_u *SourceOrganizationUpdate) AddExternalContractReferenceIDs(ids ...int) *SourceOrganizationUpdate {
	_u.mutation.AddExternalContractReferenceIDs(ids...)
	return _u
}

// AddExternalContractReferences adds the "external_contract_references" edges to the ExternalContractReference entity.
func (_u *SourceOrganizationUpdate) AddExternalContractReferences(v ...*ExternalContractReference) *SourceOrganizationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExternalContractReferenceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the EmailConversation entity by IDs.
func (_u *SourceOrganizationUpdate) AddConversationIDs(ids ...int) *SourceOrganizationUpdate {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the EmailConversation entity.
func (_u *SourceOrganizationUpdate) AddConversations(v ...*EmailConversation) *SourceOrganizationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the SourceOrganizationMutation object of the builder.
func (_u *SourceOrganizationUpdate) Mutation() *SourceOrganizationMutation {
	return _u.mutation
}

// ClearExternalContractReferences clears all "external_contract_references" edges to the ExternalContractReference entity.
func (_u *SourceOrganizationUpdate) ClearExternalContractReferences() *SourceOrganizationUpdate {
	_u.mutation.ClearExternalContractReferences()
	return _u
}

// RemoveExternalContractReferenceIDs removes the "external_contract_references" edge to ExternalContractReference entities by IDs.
func (_u *SourceOrganizationUpdate) RemoveExternalContractReferenceIDs(ids ...int) *SourceOrganizationUpdate {
	_u.mutation.RemoveExternalContractReferenceIDs(ids...)
	return _u
}

// RemoveExternalContractReferences removes "external_contract_references" edges to ExternalContractReference entities.
func (_u *SourceOrganizationUpdate) RemoveExternalContractReferences(v ...*ExternalContractReference) *SourceOrganizationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExternalContractReferenceIDs(ids...)
}

// ClearConversations clears all "conversations" edges to the EmailConversation entity.
func (_u *SourceOrganizationUpdate) ClearConversations() *SourceOrganizationUpdate {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to EmailConversation entities by IDs.
func (_u *SourceOrganizationUpdate) RemoveConversationIDs(ids ...int) *SourceOrganizationUpdate {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to EmailConversation entities.
func (_u *SourceOrganizationUpdate) RemoveConversations(v ...*EmailConversation) *SourceOrganizationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceOrganizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceOrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceOrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceOrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceOrganizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sourceorganization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceOrganizationUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := sourceorganization.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sourceorganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := sourceorganization.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.normalized_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sourceorganization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceOrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sourceorganization.Table, sourceorganization.Columns, sqlgraph.NewFieldSpec(sourceorganization.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(sourceorganization.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(sourceorganization.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sourceorganization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(sourceorganization.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailAddresses(); ok {
		_spec.SetField(sourceorganization.FieldEmailAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sourceorganization.FieldEmailAddresses, value)
		})
	}
	if _u.mutation.EmailAddressesCleared() {
		_spec.ClearField(sourceorganization.FieldEmailAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.EmailDomains(); ok {
		_spec.SetField(sourceorganization.FieldEmailDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sourceorganization.FieldEmailDomains, value)
		})
	}
	if _u.mutation.EmailDomainsCleared() {
		_spec.ClearField(sourceorganization.FieldEmailDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sourceorganization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sourceorganization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sourceorganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ExternalContractReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExternalContractReferencesIDs(); len(nodes) > 0 && !_u.mutation.ExternalContractReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExternalContractReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourceorganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceOrganizationUpdateOne is the builder for updating a single SourceOrganization entity.
type SourceOrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceOrganizationMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *SourceOrganizationUpdateOne) SetTenantID(v int) *SourceOrganizationUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SourceOrganizationUpdateOne) SetNillableTenantID(v *int) *SourceOrganizationUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *SourceOrganizationUpdateOne) AddTenantID(v int) *SourceOrganizationUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SourceOrganizationUpdateOne) SetName(v string) *SourceOrganizationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SourceOrganizationUpdateOne) SetNillableName(v *string) *SourceOrganizationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *SourceOrganizationUpdateOne) SetNormalizedName(v string) *SourceOrganizationUpdateOne {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *SourceOrganizationUpdateOne) SetNillableNormalizedName(v *string) *SourceOrganizationUpdateOne {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetEmailAddresses sets the "email_addresses" field.
func (_u *SourceOrganizationUpdateOne) SetEmailAddresses(v []string) *SourceOrganizationUpdateOne {
	_u.mutation.SetEmailAddresses(v)
	return _u
}

// AppendEmailAddresses appends value to the "email_addresses" field.
func (_u *SourceOrganizationUpdateOne) AppendEmailAddresses(v []string) *SourceOrganizationUpdateOne {
	_u.mutation.AppendEmailAddresses(v)
	return _u
}

// ClearEmailAddresses clears the value of the "email_addresses" field.
func (_u *SourceOrganizationUpdateOne) ClearEmailAddresses() *SourceOrganizationUpdateOne {
	_u.mutation.ClearEmailAddresses()
	return _u
}

// SetEmailDomains sets the "email_domains" field.
func (_u *SourceOrganizationUpdateOne) SetEmailDomains(v []string) *SourceOrganizationUpdateOne {
	_u.mutation.SetEmailDomains(v)
	return _u
}

// AppendEmailDomains appends value to the "email_domains" field.
func (_u *SourceOrganizationUpdateOne) AppendEmailDomains(v []string) *SourceOrganizationUpdateOne {
	_u.mutation.AppendEmailDomains(v)
	return _u
}

// ClearEmailDomains clears the value of the "email_domains" field.
func (_u *SourceOrganizationUpdateOne) ClearEmailDomains() *SourceOrganizationUpdateOne {
	_u.mutation.ClearEmailDomains()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceOrganizationUpdateOne) SetStatus(v string) *SourceOrganizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceOrganizationUpdateOne) SetNillableStatus(v *string) *SourceOrganizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SourceOrganizationUpdateOne) SetCreatedAt(v time.Time) *SourceOrganizationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SourceOrganizationUpdateOne) SetNillableCreatedAt(v *time.Time) *SourceOrganizationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceOrganizationUpdateOne) SetUpdatedAt(v time.Time) *SourceOrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddExternalContractReferenceIDs adds the "external_contract_references" edge to the ExternalContractReference entity by IDs.
func (_u *SourceOrganizationUpdateOne) AddExternalContractReferenceIDs(ids ...int) *SourceOrganizationUpdateOne {
	_u.mutation.AddExternalContractReferenceIDs(ids...)
	return _u
}

// AddExternalContractReferences adds the "external_contract_references" edges to the ExternalContractReference entity.
func (_u *SourceOrganizationUpdateOne) AddExternalContractReferences(v ...*ExternalContractReference) *SourceOrganizationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExternalContractReferenceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the EmailConversation entity by IDs.
func (_u *SourceOrganizationUpdateOne) AddConversationIDs(ids ...int) *SourceOrganizationUpdateOne {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the EmailConversation entity.
func (_u *SourceOrganizationUpdateOne) AddConversations(v ...*EmailConversation) *SourceOrganizationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the SourceOrganizationMutation object of the builder.
func (_u *SourceOrganizationUpdateOne) Mutation() *SourceOrganizationMutation {
	return _u.mutation
}

// ClearExternalContractReferences clears all "external_contract_references" edges to the ExternalContractReference entity.
func (_u *SourceOrganizationUpdateOne) ClearExternalContractReferences() *SourceOrganizationUpdateOne {
	_u.mutation.ClearExternalContractReferences()
	return _u
}

// RemoveExternalContractReferenceIDs removes the "external_contract_references" edge to ExternalContractReference entities by IDs.
func (_u *SourceOrganizationUpdateOne) RemoveExternalContractReferenceIDs(ids ...int) *SourceOrganizationUpdateOne {
	_u.mutation.RemoveExternalContractReferenceIDs(ids...)
	return _u
}

// RemoveExternalContractReferences removes "external_contract_references" edges to ExternalContractReference entities.
func (_u *SourceOrganizationUpdateOne) RemoveExternalContractReferences(v ...*ExternalContractReference) *SourceOrganizationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExternalContractReferenceIDs(ids...)
}

// ClearConversations clears all "conversations" edges to the EmailConversation entity.
func (_u *SourceOrganizationUpdateOne) ClearConversations() *SourceOrganizationUpdateOne {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to EmailConversation entities by IDs.
func (_u *SourceOrganizationUpdateOne) RemoveConversationIDs(ids ...int) *SourceOrganizationUpdateOne {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to EmailConversation entities.
func (_u *SourceOrganizationUpdateOne) RemoveConversations(v ...*EmailConversation) *SourceOrganizationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Where appends a list predicates to the SourceOrganizationUpdate builder.
func (_u *SourceOrganizationUpdateOne) Where(ps ...predicate.SourceOrganization) *SourceOrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceOrganizationUpdateOne) Select(field string, fields ...string) *SourceOrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SourceOrganization entity.
func (_u *SourceOrganizationUpdateOne) Save(ctx context.Context) (*SourceOrganization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceOrganizationUpdateOne) SaveX(ctx context.Context) *SourceOrganization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceOrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceOrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceOrganizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sourceorganization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceOrganizationUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := sourceorganization.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sourceorganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := sourceorganization.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.normalized_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sourceorganization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SourceOrganization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceOrganizationUpdateOne) sqlSave(ctx context.Context) (_node *SourceOrganization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sourceorganization.Table, sourceorganization.Columns, sqlgraph.NewFieldSpec(sourceorganization.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SourceOrganization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourceorganization.FieldID)
		for _, f := range fields {
			if !sourceorganization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sourceorganization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(sourceorganization.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(sourceorganization.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sourceorganization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(sourceorganization.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailAddresses(); ok {
		_spec.SetField(sourceorganization.FieldEmailAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sourceorganization.FieldEmailAddresses, value)
		})
	}
	if _u.mutation.EmailAddressesCleared() {
		_spec.ClearField(sourceorganization.FieldEmailAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.EmailDomains(); ok {
		_spec.SetField(sourceorganization.FieldEmailDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sourceorganization.FieldEmailDomains, value)
		})
	}
	if _u.mutation.EmailDomainsCleared() {
		_spec.ClearField(sourceorganization.FieldEmailDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sourceorganization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sourceorganization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sourceorganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ExternalContractReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExternalContractReferencesIDs(); len(nodes) > 0 && !_u.mutation.ExternalContractReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExternalContractReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ExternalContractReferencesTable,
			Columns: []string{sourceorganization.ExternalContractReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalcontractreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourceorganization.ConversationsTable,
			Columns: []string{sourceorganization.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SourceOrganization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourceorganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
