// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/ticketautomationrule"
	"itsm-backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// TicketAutomationRuleUpdate is the builder for updating TicketAutomationRule entities.
type TicketAutomationRuleUpdate struct {
	config
	hooks    []Hook
	mutation *TicketAutomationRuleMutation
}

// Where appends a list predicates to the TicketAutomationRuleUpdate builder.
func (taru *TicketAutomationRuleUpdate) Where(ps ...predicate.TicketAutomationRule) *TicketAutomationRuleUpdate {
	taru.mutation.Where(ps...)
	return taru
}

// SetName sets the "name" field.
func (taru *TicketAutomationRuleUpdate) SetName(s string) *TicketAutomationRuleUpdate {
	taru.mutation.SetName(s)
	return taru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableName(s *string) *TicketAutomationRuleUpdate {
	if s != nil {
		taru.SetName(*s)
	}
	return taru
}

// SetDescription sets the "description" field.
func (taru *TicketAutomationRuleUpdate) SetDescription(s string) *TicketAutomationRuleUpdate {
	taru.mutation.SetDescription(s)
	return taru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableDescription(s *string) *TicketAutomationRuleUpdate {
	if s != nil {
		taru.SetDescription(*s)
	}
	return taru
}

// ClearDescription clears the value of the "description" field.
func (taru *TicketAutomationRuleUpdate) ClearDescription() *TicketAutomationRuleUpdate {
	taru.mutation.ClearDescription()
	return taru
}

// SetPriority sets the "priority" field.
func (taru *TicketAutomationRuleUpdate) SetPriority(i int) *TicketAutomationRuleUpdate {
	taru.mutation.ResetPriority()
	taru.mutation.SetPriority(i)
	return taru
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillablePriority(i *int) *TicketAutomationRuleUpdate {
	if i != nil {
		taru.SetPriority(*i)
	}
	return taru
}

// AddPriority adds i to the "priority" field.
func (taru *TicketAutomationRuleUpdate) AddPriority(i int) *TicketAutomationRuleUpdate {
	taru.mutation.AddPriority(i)
	return taru
}

// SetConditions sets the "conditions" field.
func (taru *TicketAutomationRuleUpdate) SetConditions(m []map[string]interface{}) *TicketAutomationRuleUpdate {
	taru.mutation.SetConditions(m)
	return taru
}

// AppendConditions appends m to the "conditions" field.
func (taru *TicketAutomationRuleUpdate) AppendConditions(m []map[string]interface{}) *TicketAutomationRuleUpdate {
	taru.mutation.AppendConditions(m)
	return taru
}

// ClearConditions clears the value of the "conditions" field.
func (taru *TicketAutomationRuleUpdate) ClearConditions() *TicketAutomationRuleUpdate {
	taru.mutation.ClearConditions()
	return taru
}

// SetActions sets the "actions" field.
func (taru *TicketAutomationRuleUpdate) SetActions(m []map[string]interface{}) *TicketAutomationRuleUpdate {
	taru.mutation.SetActions(m)
	return taru
}

// AppendActions appends m to the "actions" field.
func (taru *TicketAutomationRuleUpdate) AppendActions(m []map[string]interface{}) *TicketAutomationRuleUpdate {
	taru.mutation.AppendActions(m)
	return taru
}

// ClearActions clears the value of the "actions" field.
func (taru *TicketAutomationRuleUpdate) ClearActions() *TicketAutomationRuleUpdate {
	taru.mutation.ClearActions()
	return taru
}

// SetIsActive sets the "is_active" field.
func (taru *TicketAutomationRuleUpdate) SetIsActive(b bool) *TicketAutomationRuleUpdate {
	taru.mutation.SetIsActive(b)
	return taru
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableIsActive(b *bool) *TicketAutomationRuleUpdate {
	if b != nil {
		taru.SetIsActive(*b)
	}
	return taru
}

// SetExecutionCount sets the "execution_count" field.
func (taru *TicketAutomationRuleUpdate) SetExecutionCount(i int) *TicketAutomationRuleUpdate {
	taru.mutation.ResetExecutionCount()
	taru.mutation.SetExecutionCount(i)
	return taru
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableExecutionCount(i *int) *TicketAutomationRuleUpdate {
	if i != nil {
		taru.SetExecutionCount(*i)
	}
	return taru
}

// AddExecutionCount adds i to the "execution_count" field.
func (taru *TicketAutomationRuleUpdate) AddExecutionCount(i int) *TicketAutomationRuleUpdate {
	taru.mutation.AddExecutionCount(i)
	return taru
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (taru *TicketAutomationRuleUpdate) SetLastExecutedAt(t time.Time) *TicketAutomationRuleUpdate {
	taru.mutation.SetLastExecutedAt(t)
	return taru
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableLastExecutedAt(t *time.Time) *TicketAutomationRuleUpdate {
	if t != nil {
		taru.SetLastExecutedAt(*t)
	}
	return taru
}

// ClearLastExecutedAt clears the value of the "last_executed_at" field.
func (taru *TicketAutomationRuleUpdate) ClearLastExecutedAt() *TicketAutomationRuleUpdate {
	taru.mutation.ClearLastExecutedAt()
	return taru
}

// SetCreatedBy sets the "created_by" field.
func (taru *TicketAutomationRuleUpdate) SetCreatedBy(i int) *TicketAutomationRuleUpdate {
	taru.mutation.SetCreatedBy(i)
	return taru
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableCreatedBy(i *int) *TicketAutomationRuleUpdate {
	if i != nil {
		taru.SetCreatedBy(*i)
	}
	return taru
}

// SetTenantID sets the "tenant_id" field.
func (taru *TicketAutomationRuleUpdate) SetTenantID(i int) *TicketAutomationRuleUpdate {
	taru.mutation.ResetTenantID()
	taru.mutation.SetTenantID(i)
	return taru
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableTenantID(i *int) *TicketAutomationRuleUpdate {
	if i != nil {
		taru.SetTenantID(*i)
	}
	return taru
}

// AddTenantID adds i to the "tenant_id" field.
func (taru *TicketAutomationRuleUpdate) AddTenantID(i int) *TicketAutomationRuleUpdate {
	taru.mutation.AddTenantID(i)
	return taru
}

// SetCreatedAt sets the "created_at" field.
func (taru *TicketAutomationRuleUpdate) SetCreatedAt(t time.Time) *TicketAutomationRuleUpdate {
	taru.mutation.SetCreatedAt(t)
	return taru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (taru *TicketAutomationRuleUpdate) SetNillableCreatedAt(t *time.Time) *TicketAutomationRuleUpdate {
	if t != nil {
		taru.SetCreatedAt(*t)
	}
	return taru
}

// SetUpdatedAt sets the "updated_at" field.
func (taru *TicketAutomationRuleUpdate) SetUpdatedAt(t time.Time) *TicketAutomationRuleUpdate {
	taru.mutation.SetUpdatedAt(t)
	return taru
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (taru *TicketAutomationRuleUpdate) SetCreatorID(id int) *TicketAutomationRuleUpdate {
	taru.mutation.SetCreatorID(id)
	return taru
}

// SetCreator sets the "creator" edge to the User entity.
func (taru *TicketAutomationRuleUpdate) SetCreator(u *User) *TicketAutomationRuleUpdate {
	return taru.SetCreatorID(u.ID)
}

// Mutation returns the TicketAutomationRuleMutation object of the builder.
func (taru *TicketAutomationRuleUpdate) Mutation() *TicketAutomationRuleMutation {
	return taru.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (taru *TicketAutomationRuleUpdate) ClearCreator() *TicketAutomationRuleUpdate {
	taru.mutation.ClearCreator()
	return taru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (taru *TicketAutomationRuleUpdate) Save(ctx context.Context) (int, error) {
	taru.defaults()
	return withHooks(ctx, taru.sqlSave, taru.mutation, taru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (taru *TicketAutomationRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := taru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (taru *TicketAutomationRuleUpdate) Exec(ctx context.Context) error {
	_, err := taru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (taru *TicketAutomationRuleUpdate) ExecX(ctx context.Context) {
	if err := taru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (taru *TicketAutomationRuleUpdate) defaults() {
	if _, ok := taru.mutation.UpdatedAt(); !ok {
		v := ticketautomationrule.UpdateDefaultUpdatedAt()
		taru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (taru *TicketAutomationRuleUpdate) check() error {
	if v, ok := taru.mutation.Name(); ok {
		if err := ticketautomationrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.name": %w`, err)}
		}
	}
	if v, ok := taru.mutation.CreatedBy(); ok {
		if err := ticketautomationrule.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.created_by": %w`, err)}
		}
	}
	if v, ok := taru.mutation.TenantID(); ok {
		if err := ticketautomationrule.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.tenant_id": %w`, err)}
		}
	}
	if taru.mutation.CreatorCleared() && len(taru.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketAutomationRule.creator"`)
	}
	return nil
}

func (taru *TicketAutomationRuleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := taru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketautomationrule.Table, ticketautomationrule.Columns, sqlgraph.NewFieldSpec(ticketautomationrule.FieldID, field.TypeInt))
	if ps := taru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := taru.mutation.Name(); ok {
		_spec.SetField(ticketautomationrule.FieldName, field.TypeString, value)
	}
	if value, ok := taru.mutation.Description(); ok {
		_spec.SetField(ticketautomationrule.FieldDescription, field.TypeString, value)
	}
	if taru.mutation.DescriptionCleared() {
		_spec.ClearField(ticketautomationrule.FieldDescription, field.TypeString)
	}
	if value, ok := taru.mutation.Priority(); ok {
		_spec.SetField(ticketautomationrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := taru.mutation.AddedPriority(); ok {
		_spec.AddField(ticketautomationrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := taru.mutation.Conditions(); ok {
		_spec.SetField(ticketautomationrule.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := taru.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ticketautomationrule.FieldConditions, value)
		})
	}
	if taru.mutation.ConditionsCleared() {
		_spec.ClearField(ticketautomationrule.FieldConditions, field.TypeJSON)
	}
	if value, ok := taru.mutation.Actions(); ok {
		_spec.SetField(ticketautomationrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := taru.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ticketautomationrule.FieldActions, value)
		})
	}
	if taru.mutation.ActionsCleared() {
		_spec.ClearField(ticketautomationrule.FieldActions, field.TypeJSON)
	}
	if value, ok := taru.mutation.IsActive(); ok {
		_spec.SetField(ticketautomationrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := taru.mutation.ExecutionCount(); ok {
		_spec.SetField(ticketautomationrule.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := taru.mutation.AddedExecutionCount(); ok {
		_spec.AddField(ticketautomationrule.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := taru.mutation.LastExecutedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldLastExecutedAt, field.TypeTime, value)
	}
	if taru.mutation.LastExecutedAtCleared() {
		_spec.ClearField(ticketautomationrule.FieldLastExecutedAt, field.TypeTime)
	}
	if value, ok := taru.mutation.TenantID(); ok {
		_spec.SetField(ticketautomationrule.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := taru.mutation.AddedTenantID(); ok {
		_spec.AddField(ticketautomationrule.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := taru.mutation.CreatedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := taru.mutation.UpdatedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if taru.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketautomationrule.CreatorTable,
			Columns: []string{ticketautomationrule.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := taru.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketautomationrule.CreatorTable,
			Columns: []string{ticketautomationrule.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, taru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketautomationrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	taru.mutation.done = true
	return n, nil
}

// TicketAutomationRuleUpdateOne is the builder for updating a single TicketAutomationRule entity.
type TicketAutomationRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketAutomationRuleMutation
}

// SetName sets the "name" field.
func (taruo *TicketAutomationRuleUpdateOne) SetName(s string) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetName(s)
	return taruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableName(s *string) *TicketAutomationRuleUpdateOne {
	if s != nil {
		taruo.SetName(*s)
	}
	return taruo
}

// SetDescription sets the "description" field.
func (taruo *TicketAutomationRuleUpdateOne) SetDescription(s string) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetDescription(s)
	return taruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableDescription(s *string) *TicketAutomationRuleUpdateOne {
	if s != nil {
		taruo.SetDescription(*s)
	}
	return taruo
}

// ClearDescription clears the value of the "description" field.
func (taruo *TicketAutomationRuleUpdateOne) ClearDescription() *TicketAutomationRuleUpdateOne {
	taruo.mutation.ClearDescription()
	return taruo
}

// SetPriority sets the "priority" field.
func (taruo *TicketAutomationRuleUpdateOne) SetPriority(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.ResetPriority()
	taruo.mutation.SetPriority(i)
	return taruo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillablePriority(i *int) *TicketAutomationRuleUpdateOne {
	if i != nil {
		taruo.SetPriority(*i)
	}
	return taruo
}

// AddPriority adds i to the "priority" field.
func (taruo *TicketAutomationRuleUpdateOne) AddPriority(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.AddPriority(i)
	return taruo
}

// SetConditions sets the "conditions" field.
func (taruo *TicketAutomationRuleUpdateOne) SetConditions(m []map[string]interface{}) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetConditions(m)
	return taruo
}

// AppendConditions appends m to the "conditions" field.
func (taruo *TicketAutomationRuleUpdateOne) AppendConditions(m []map[string]interface{}) *TicketAutomationRuleUpdateOne {
	taruo.mutation.AppendConditions(m)
	return taruo
}

// ClearConditions clears the value of the "conditions" field.
func (taruo *TicketAutomationRuleUpdateOne) ClearConditions() *TicketAutomationRuleUpdateOne {
	taruo.mutation.ClearConditions()
	return taruo
}

// SetActions sets the "actions" field.
func (taruo *TicketAutomationRuleUpdateOne) SetActions(m []map[string]interface{}) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetActions(m)
	return taruo
}

// AppendActions appends m to the "actions" field.
func (taruo *TicketAutomationRuleUpdateOne) AppendActions(m []map[string]interface{}) *TicketAutomationRuleUpdateOne {
	taruo.mutation.AppendActions(m)
	return taruo
}

// ClearActions clears the value of the "actions" field.
func (taruo *TicketAutomationRuleUpdateOne) ClearActions() *TicketAutomationRuleUpdateOne {
	taruo.mutation.ClearActions()
	return taruo
}

// SetIsActive sets the "is_active" field.
func (taruo *TicketAutomationRuleUpdateOne) SetIsActive(b bool) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetIsActive(b)
	return taruo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableIsActive(b *bool) *TicketAutomationRuleUpdateOne {
	if b != nil {
		taruo.SetIsActive(*b)
	}
	return taruo
}

// SetExecutionCount sets the "execution_count" field.
func (taruo *TicketAutomationRuleUpdateOne) SetExecutionCount(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.ResetExecutionCount()
	taruo.mutation.SetExecutionCount(i)
	return taruo
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableExecutionCount(i *int) *TicketAutomationRuleUpdateOne {
	if i != nil {
		taruo.SetExecutionCount(*i)
	}
	return taruo
}

// AddExecutionCount adds i to the "execution_count" field.
func (taruo *TicketAutomationRuleUpdateOne) AddExecutionCount(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.AddExecutionCount(i)
	return taruo
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (taruo *TicketAutomationRuleUpdateOne) SetLastExecutedAt(t time.Time) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetLastExecutedAt(t)
	return taruo
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableLastExecutedAt(t *time.Time) *TicketAutomationRuleUpdateOne {
	if t != nil {
		taruo.SetLastExecutedAt(*t)
	}
	return taruo
}

// ClearLastExecutedAt clears the value of the "last_executed_at" field.
func (taruo *TicketAutomationRuleUpdateOne) ClearLastExecutedAt() *TicketAutomationRuleUpdateOne {
	taruo.mutation.ClearLastExecutedAt()
	return taruo
}

// SetCreatedBy sets the "created_by" field.
func (taruo *TicketAutomationRuleUpdateOne) SetCreatedBy(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetCreatedBy(i)
	return taruo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableCreatedBy(i *int) *TicketAutomationRuleUpdateOne {
	if i != nil {
		taruo.SetCreatedBy(*i)
	}
	return taruo
}

// SetTenantID sets the "tenant_id" field.
func (taruo *TicketAutomationRuleUpdateOne) SetTenantID(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.ResetTenantID()
	taruo.mutation.SetTenantID(i)
	return taruo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableTenantID(i *int) *TicketAutomationRuleUpdateOne {
	if i != nil {
		taruo.SetTenantID(*i)
	}
	return taruo
}

// AddTenantID adds i to the "tenant_id" field.
func (taruo *TicketAutomationRuleUpdateOne) AddTenantID(i int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.AddTenantID(i)
	return taruo
}

// SetCreatedAt sets the "created_at" field.
func (taruo *TicketAutomationRuleUpdateOne) SetCreatedAt(t time.Time) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetCreatedAt(t)
	return taruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (taruo *TicketAutomationRuleUpdateOne) SetNillableCreatedAt(t *time.Time) *TicketAutomationRuleUpdateOne {
	if t != nil {
		taruo.SetCreatedAt(*t)
	}
	return taruo
}

// SetUpdatedAt sets the "updated_at" field.
func (taruo *TicketAutomationRuleUpdateOne) SetUpdatedAt(t time.Time) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetUpdatedAt(t)
	return taruo
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (taruo *TicketAutomationRuleUpdateOne) SetCreatorID(id int) *TicketAutomationRuleUpdateOne {
	taruo.mutation.SetCreatorID(id)
	return taruo
}

// SetCreator sets the "creator" edge to the User entity.
func (taruo *TicketAutomationRuleUpdateOne) SetCreator(u *User) *TicketAutomationRuleUpdateOne {
	return taruo.SetCreatorID(u.ID)
}

// Mutation returns the TicketAutomationRuleMutation object of the builder.
func (taruo *TicketAutomationRuleUpdateOne) Mutation() *TicketAutomationRuleMutation {
	return taruo.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (taruo *TicketAutomationRuleUpdateOne) ClearCreator() *TicketAutomationRuleUpdateOne {
	taruo.mutation.ClearCreator()
	return taruo
}

// Where appends a list predicates to the TicketAutomationRuleUpdate builder.
func (taruo *TicketAutomationRuleUpdateOne) Where(ps ...predicate.TicketAutomationRule) *TicketAutomationRuleUpdateOne {
	taruo.mutation.Where(ps...)
	return taruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (taruo *TicketAutomationRuleUpdateOne) Select(field string, fields ...string) *TicketAutomationRuleUpdateOne {
	taruo.fields = append([]string{field}, fields...)
	return taruo
}

// Save executes the query and returns the updated TicketAutomationRule entity.
func (taruo *TicketAutomationRuleUpdateOne) Save(ctx context.Context) (*TicketAutomationRule, error) {
	taruo.defaults()
	return withHooks(ctx, taruo.sqlSave, taruo.mutation, taruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (taruo *TicketAutomationRuleUpdateOne) SaveX(ctx context.Context) *TicketAutomationRule {
	node, err := taruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (taruo *TicketAutomationRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := taruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (taruo *TicketAutomationRuleUpdateOne) ExecX(ctx context.Context) {
	if err := taruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (taruo *TicketAutomationRuleUpdateOne) defaults() {
	if _, ok := taruo.mutation.UpdatedAt(); !ok {
		v := ticketautomationrule.UpdateDefaultUpdatedAt()
		taruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (taruo *TicketAutomationRuleUpdateOne) check() error {
	if v, ok := taruo.mutation.Name(); ok {
		if err := ticketautomationrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.name": %w`, err)}
		}
	}
	if v, ok := taruo.mutation.CreatedBy(); ok {
		if err := ticketautomationrule.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.created_by": %w`, err)}
		}
	}
	if v, ok := taruo.mutation.TenantID(); ok {
		if err := ticketautomationrule.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TicketAutomationRule.tenant_id": %w`, err)}
		}
	}
	if taruo.mutation.CreatorCleared() && len(taruo.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketAutomationRule.creator"`)
	}
	return nil
}

func (taruo *TicketAutomationRuleUpdateOne) sqlSave(ctx context.Context) (_node *TicketAutomationRule, err error) {
	if err := taruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketautomationrule.Table, ticketautomationrule.Columns, sqlgraph.NewFieldSpec(ticketautomationrule.FieldID, field.TypeInt))
	id, ok := taruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketAutomationRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := taruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketautomationrule.FieldID)
		for _, f := range fields {
			if !ticketautomationrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketautomationrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := taruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := taruo.mutation.Name(); ok {
		_spec.SetField(ticketautomationrule.FieldName, field.TypeString, value)
	}
	if value, ok := taruo.mutation.Description(); ok {
		_spec.SetField(ticketautomationrule.FieldDescription, field.TypeString, value)
	}
	if taruo.mutation.DescriptionCleared() {
		_spec.ClearField(ticketautomationrule.FieldDescription, field.TypeString)
	}
	if value, ok := taruo.mutation.Priority(); ok {
		_spec.SetField(ticketautomationrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.AddedPriority(); ok {
		_spec.AddField(ticketautomationrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.Conditions(); ok {
		_spec.SetField(ticketautomationrule.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := taruo.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ticketautomationrule.FieldConditions, value)
		})
	}
	if taruo.mutation.ConditionsCleared() {
		_spec.ClearField(ticketautomationrule.FieldConditions, field.TypeJSON)
	}
	if value, ok := taruo.mutation.Actions(); ok {
		_spec.SetField(ticketautomationrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := taruo.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ticketautomationrule.FieldActions, value)
		})
	}
	if taruo.mutation.ActionsCleared() {
		_spec.ClearField(ticketautomationrule.FieldActions, field.TypeJSON)
	}
	if value, ok := taruo.mutation.IsActive(); ok {
		_spec.SetField(ticketautomationrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := taruo.mutation.ExecutionCount(); ok {
		_spec.SetField(ticketautomationrule.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.AddedExecutionCount(); ok {
		_spec.AddField(ticketautomationrule.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.LastExecutedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldLastExecutedAt, field.TypeTime, value)
	}
	if taruo.mutation.LastExecutedAtCleared() {
		_spec.ClearField(ticketautomationrule.FieldLastExecutedAt, field.TypeTime)
	}
	if value, ok := taruo.mutation.TenantID(); ok {
		_spec.SetField(ticketautomationrule.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.AddedTenantID(); ok {
		_spec.AddField(ticketautomationrule.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := taruo.mutation.CreatedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := taruo.mutation.UpdatedAt(); ok {
		_spec.SetField(ticketautomationrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if taruo.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketautomationrule.CreatorTable,
			Columns: []string{ticketautomationrule.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := taruo.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketautomationrule.CreatorTable,
			Columns: []string{ticketautomationrule.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketAutomationRule{config: taruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, taruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketautomationrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	taruo.mutation.done = true
	return _node, nil
}
