// Code generated by ent, DO NOT EDIT.

package cmdbexporttask

import (
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTaskID, v))
}

// ExportType applies equality check predicate on the "export_type" field. It's identical to ExportTypeEQ.
func ExportType(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldExportType, v))
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldFileURL, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldFileSize, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTotalCount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldErrorMessage, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorName applies equality check predicate on the "operator_name" field. It's identical to OperatorNameEQ.
func OperatorName(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldOperatorName, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldCreatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldCompletedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldExpiresAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldTaskID, v))
}

// FiltersIsNil applies the IsNil predicate on the "filters" field.
func FiltersIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldFilters))
}

// FiltersNotNil applies the NotNil predicate on the "filters" field.
func FiltersNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldFilters))
}

// ExportFieldsIsNil applies the IsNil predicate on the "export_fields" field.
func ExportFieldsIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldExportFields))
}

// ExportFieldsNotNil applies the NotNil predicate on the "export_fields" field.
func ExportFieldsNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldExportFields))
}

// ExportTypeEQ applies the EQ predicate on the "export_type" field.
func ExportTypeEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldExportType, v))
}

// ExportTypeNEQ applies the NEQ predicate on the "export_type" field.
func ExportTypeNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldExportType, v))
}

// ExportTypeIn applies the In predicate on the "export_type" field.
func ExportTypeIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldExportType, vs...))
}

// ExportTypeNotIn applies the NotIn predicate on the "export_type" field.
func ExportTypeNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldExportType, vs...))
}

// ExportTypeGT applies the GT predicate on the "export_type" field.
func ExportTypeGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldExportType, v))
}

// ExportTypeGTE applies the GTE predicate on the "export_type" field.
func ExportTypeGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldExportType, v))
}

// ExportTypeLT applies the LT predicate on the "export_type" field.
func ExportTypeLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldExportType, v))
}

// ExportTypeLTE applies the LTE predicate on the "export_type" field.
func ExportTypeLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldExportType, v))
}

// ExportTypeContains applies the Contains predicate on the "export_type" field.
func ExportTypeContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldExportType, v))
}

// ExportTypeHasPrefix applies the HasPrefix predicate on the "export_type" field.
func ExportTypeHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldExportType, v))
}

// ExportTypeHasSuffix applies the HasSuffix predicate on the "export_type" field.
func ExportTypeHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldExportType, v))
}

// ExportTypeEqualFold applies the EqualFold predicate on the "export_type" field.
func ExportTypeEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldExportType, v))
}

// ExportTypeContainsFold applies the ContainsFold predicate on the "export_type" field.
func ExportTypeContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldExportType, v))
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldFileURL, v))
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldFileURL, v))
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldFileURL, vs...))
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldFileURL, vs...))
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldFileURL, v))
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldFileURL, v))
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldFileURL, v))
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldFileURL, v))
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldFileURL, v))
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldFileURL, v))
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldFileURL, v))
}

// FileURLIsNil applies the IsNil predicate on the "file_url" field.
func FileURLIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldFileURL))
}

// FileURLNotNil applies the NotNil predicate on the "file_url" field.
func FileURLNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldFileURL))
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldFileURL, v))
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldFileURL, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldFileSize, v))
}

// FileSizeIsNil applies the IsNil predicate on the "file_size" field.
func FileSizeIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldFileSize))
}

// FileSizeNotNil applies the NotNil predicate on the "file_size" field.
func FileSizeNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldFileSize))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldTotalCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorNameEQ applies the EQ predicate on the "operator_name" field.
func OperatorNameEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldOperatorName, v))
}

// OperatorNameNEQ applies the NEQ predicate on the "operator_name" field.
func OperatorNameNEQ(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldOperatorName, v))
}

// OperatorNameIn applies the In predicate on the "operator_name" field.
func OperatorNameIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldOperatorName, vs...))
}

// OperatorNameNotIn applies the NotIn predicate on the "operator_name" field.
func OperatorNameNotIn(vs ...string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldOperatorName, vs...))
}

// OperatorNameGT applies the GT predicate on the "operator_name" field.
func OperatorNameGT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldOperatorName, v))
}

// OperatorNameGTE applies the GTE predicate on the "operator_name" field.
func OperatorNameGTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldOperatorName, v))
}

// OperatorNameLT applies the LT predicate on the "operator_name" field.
func OperatorNameLT(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldOperatorName, v))
}

// OperatorNameLTE applies the LTE predicate on the "operator_name" field.
func OperatorNameLTE(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldOperatorName, v))
}

// OperatorNameContains applies the Contains predicate on the "operator_name" field.
func OperatorNameContains(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContains(FieldOperatorName, v))
}

// OperatorNameHasPrefix applies the HasPrefix predicate on the "operator_name" field.
func OperatorNameHasPrefix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasPrefix(FieldOperatorName, v))
}

// OperatorNameHasSuffix applies the HasSuffix predicate on the "operator_name" field.
func OperatorNameHasSuffix(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldHasSuffix(FieldOperatorName, v))
}

// OperatorNameIsNil applies the IsNil predicate on the "operator_name" field.
func OperatorNameIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldOperatorName))
}

// OperatorNameNotNil applies the NotNil predicate on the "operator_name" field.
func OperatorNameNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldOperatorName))
}

// OperatorNameEqualFold applies the EqualFold predicate on the "operator_name" field.
func OperatorNameEqualFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEqualFold(FieldOperatorName, v))
}

// OperatorNameContainsFold applies the ContainsFold predicate on the "operator_name" field.
func OperatorNameContainsFold(v string) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldContainsFold(FieldOperatorName, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldCreatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldCompletedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CMDBExportTask) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CMDBExportTask) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CMDBExportTask) predicate.CMDBExportTask {
	return predicate.CMDBExportTask(sql.NotPredicates(p))
}
