-- Retired 2026-10-01: this seed referenced objects Ent never created and blocked fresh-install bootstrap
--
-- 原脚本（1516 行）在全新数据库上必然以 42P01 失败并中断整个初始化，
-- backend/worker/frontend/nginx 全部无法启动（2026-10-01 清卷全新部署实证，报错位置
-- 1367:13）。退役依据是以下实测事实：
--
--  1. 对象名与 Ent 生成的真实 schema 不一致。脚本使用 permission_definition / role /
--     role_permission，实际表为 permission_definitions / roles / role_permissions；
--     ON CONFLICT 引用的约束 permission_definition_resource_action_key 从未生成，权限
--     目录表也没有 (resource, action) 唯一索引。
--  2. 脚本自建的 endpoint_acls 不是 Ent 表。Go 类型 EndpointACL 的表名是
--     endpoint_ac_ls（ent/endpointacl/endpointacl.go:39），middleware/smart_permission.go
--     的 L2 数据库 ACL 只读后者，前者没有任何读取方。
--  3. 权限基线另有权威所有者。pkg/seeder（permissions、roles、role permission bindings）
--     按租户幂等播种；migrations/20260501_enable_rbac_from_db.sql 继续提供 roles 基线；
--     Ent 的 permission_definitions 当前没有应用读取方。
--  4. 该脚本的效果从未在任何真实安装中生效。目录自发现上线（2026-09-08）后，既有安装对
--     日期化迁移一律「收养不执行」（migration/legacy_record.go adoptionCutoffUTC），只有
--     全新安装才会执行它——即全新安装必然失败、既有安装从未受益。
--
-- 若要恢复动态端点 ACL 能力，必须按 endpoint_ac_ls 重写，并在同一变更内证明：条目化
-- tenant_id 过滤；L2「ACL 命中但角色无权限即拒绝」与 L3 URL 推断（middleware/rbac.go
-- ResourceActionMap）之间的优先级影响；super_admin 之外角色的授权与跨租户拒绝回归测试。
-- 不要复制本脚本的旧对象名。原文按同一版本名保留在 git 历史中。
SELECT 1;
