-- Retired 2026-10-01: marketplace tables come from Ent and catalog rows come from the seeder
--
-- 原脚本（建表 + 5 条目录种子）在全新数据库上以 not-null violation 失败并中断初始化
-- （2026-10-01 清卷全新部署实证，报错位置 96：null value in column "created_at" of
-- relation "marketplace_items"）。实测依据：
--
--  1. 建表段是死代码。marketplace_items / item_versions / tenant_installations 已由
--     Ent auto-migrate 先建好（全新库迁移执行前三表已存在），脚本的
--     CREATE TABLE IF NOT EXISTS 全部为空操作，因此脚本 DDL 里的
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW() 从未生效——真实列由
--     ent/schema/marketplace_item.go:97 生成，数据库层没有默认值，种子 INSERT 不带
--     时间戳必然违反 NOT NULL。
--  2. 目录行已有所有者。pkg/seeder/seeder.go:2457 seedMarketplaceItems 幂等播种同名
--     目录条目并显式 SetCreatedAt/SetUpdatedAt，播种清单见
--     pkg/seeder/manifest_definitions.go:229（feishu-connector 等）。清卷前旧库实测
--     marketplace_items=5 行且 created_at 有值，即来自 seeder 而非本脚本（该版本账本
--     checksum 为空，从未执行）。
--
-- 需要新增/调整市场目录条目时改 pkg/seeder/manifest_definitions.go；需要调整列结构时改
-- ent/schema 并重新生成，不要在这里继续维护第二套 DDL 与种子。
SELECT 1;
