-- Retired 2026-10-01: menu reparenting asserted hardcoded menu IDs and can only run after seeding
--
-- 原脚本在全新数据库上以 RAISE EXCEPTION 失败并中断初始化（2026-10-01 清卷全新部署实证，
--报错位置 46：parent /tickets (id=2) not found）。实测依据：
--
--  1. 迁移在 seed 之前运行，此时 menus 为空表，脚本开头的「安全断言」必然命中
--     RAISE EXCEPTION。断言本身也依赖 id=2/15/34/40 这类单机安装里自增出来的菜单主键：
--     清卷前旧库实测 /tickets 的 id 是 3，不是 2 —— 主键跨安装不稳定，脚本不可重放。
--  2. 脚本所有语句硬编码 tenant_id = 1，违反「新增查询/写入必须租户过滤」的项目约束。
--  3. 归位目标已由唯一所有者表达：pkg/menubaseline/baseline.go:57 把「工单类型」声明为
--     ParentPath '/tickets'、SortOrder 21，「工单统计」同域归位，seeder 按租户幂等播种整棵树。
--     清卷前旧库实测 /tickets/types 与 /tickets/analytics 的 parent_path 均为 /tickets，
--     /audit-logs 与 /notifications 已为顶级，/workflow/audit 挂在 /workflow 下 —— 目标形态
--     已存在。该版本账本 checksum 为空，从未执行。
--
-- 后续若还要调整菜单形态，改 pkg/menubaseline/baseline.go 并更新其 reconcile 测试；
-- 不要在迁移里按主键 id 或固定租户改菜单数据。
SELECT 1;
