// Code generated by ent, DO NOT EDIT.

package migrations

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/schema"
	"itsm-backend/migrations/approvalchain"
	"itsm-backend/migrations/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ApprovalChainUpdate is the builder for updating ApprovalChain entities.
type ApprovalChainUpdate struct {
	config
	hooks    []Hook
	mutation *ApprovalChainMutation
}

// Where appends a list predicates to the ApprovalChainUpdate builder.
func (_u *ApprovalChainUpdate) Where(ps ...predicate.ApprovalChain) *ApprovalChainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ApprovalChainUpdate) SetName(v string) *ApprovalChainUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableName(v *string) *ApprovalChainUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApprovalChainUpdate) SetDescription(v string) *ApprovalChainUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableDescription(v *string) *ApprovalChainUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApprovalChainUpdate) ClearDescription() *ApprovalChainUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *ApprovalChainUpdate) SetEntityType(v string) *ApprovalChainUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableEntityType(v *string) *ApprovalChainUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetChain sets the "chain" field.
func (_u *ApprovalChainUpdate) SetChain(v []schema.ApprovalChainStep) *ApprovalChainUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// AppendChain appends value to the "chain" field.
func (_u *ApprovalChainUpdate) AppendChain(v []schema.ApprovalChainStep) *ApprovalChainUpdate {
	_u.mutation.AppendChain(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalChainUpdate) SetStatus(v string) *ApprovalChainUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableStatus(v *string) *ApprovalChainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApprovalChainUpdate) SetCreatedBy(v int) *ApprovalChainUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableCreatedBy(v *int) *ApprovalChainUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ApprovalChainUpdate) AddCreatedBy(v int) *ApprovalChainUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApprovalChainUpdate) ClearCreatedBy() *ApprovalChainUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ApprovalChainUpdate) SetTenantID(v int) *ApprovalChainUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableTenantID(v *int) *ApprovalChainUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ApprovalChainUpdate) AddTenantID(v int) *ApprovalChainUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ApprovalChainUpdate) ClearTenantID() *ApprovalChainUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ApprovalChainUpdate) SetCreatedAt(v time.Time) *ApprovalChainUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ApprovalChainUpdate) SetNillableCreatedAt(v *time.Time) *ApprovalChainUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalChainUpdate) SetUpdatedAt(v time.Time) *ApprovalChainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ApprovalChainMutation object of the builder.
func (_u *ApprovalChainUpdate) Mutation() *ApprovalChainMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApprovalChainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalChainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApprovalChainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalChainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApprovalChainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := approvalchain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalChainUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := approvalchain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`migrations: validator failed for field "ApprovalChain.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ApprovalChainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalchain.Table, approvalchain.Columns, sqlgraph.NewFieldSpec(approvalchain.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(approvalchain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(approvalchain.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(approvalchain.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(approvalchain.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(approvalchain.FieldChain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalchain.FieldChain, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalchain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(approvalchain.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(approvalchain.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(approvalchain.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(approvalchain.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(approvalchain.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(approvalchain.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(approvalchain.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalchain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalchain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApprovalChainUpdateOne is the builder for updating a single ApprovalChain entity.
type ApprovalChainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApprovalChainMutation
}

// SetName sets the "name" field.
func (_u *ApprovalChainUpdateOne) SetName(v string) *ApprovalChainUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableName(v *string) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApprovalChainUpdateOne) SetDescription(v string) *ApprovalChainUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableDescription(v *string) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApprovalChainUpdateOne) ClearDescription() *ApprovalChainUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *ApprovalChainUpdateOne) SetEntityType(v string) *ApprovalChainUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableEntityType(v *string) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetChain sets the "chain" field.
func (_u *ApprovalChainUpdateOne) SetChain(v []schema.ApprovalChainStep) *ApprovalChainUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// AppendChain appends value to the "chain" field.
func (_u *ApprovalChainUpdateOne) AppendChain(v []schema.ApprovalChainStep) *ApprovalChainUpdateOne {
	_u.mutation.AppendChain(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalChainUpdateOne) SetStatus(v string) *ApprovalChainUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableStatus(v *string) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApprovalChainUpdateOne) SetCreatedBy(v int) *ApprovalChainUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableCreatedBy(v *int) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ApprovalChainUpdateOne) AddCreatedBy(v int) *ApprovalChainUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApprovalChainUpdateOne) ClearCreatedBy() *ApprovalChainUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ApprovalChainUpdateOne) SetTenantID(v int) *ApprovalChainUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableTenantID(v *int) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ApprovalChainUpdateOne) AddTenantID(v int) *ApprovalChainUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ApprovalChainUpdateOne) ClearTenantID() *ApprovalChainUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ApprovalChainUpdateOne) SetCreatedAt(v time.Time) *ApprovalChainUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ApprovalChainUpdateOne) SetNillableCreatedAt(v *time.Time) *ApprovalChainUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalChainUpdateOne) SetUpdatedAt(v time.Time) *ApprovalChainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ApprovalChainMutation object of the builder.
func (_u *ApprovalChainUpdateOne) Mutation() *ApprovalChainMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApprovalChainUpdate builder.
func (_u *ApprovalChainUpdateOne) Where(ps ...predicate.ApprovalChain) *ApprovalChainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApprovalChainUpdateOne) Select(field string, fields ...string) *ApprovalChainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApprovalChain entity.
func (_u *ApprovalChainUpdateOne) Save(ctx context.Context) (*ApprovalChain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalChainUpdateOne) SaveX(ctx context.Context) *ApprovalChain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApprovalChainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalChainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApprovalChainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := approvalchain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalChainUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := approvalchain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`migrations: validator failed for field "ApprovalChain.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ApprovalChainUpdateOne) sqlSave(ctx context.Context) (_node *ApprovalChain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalchain.Table, approvalchain.Columns, sqlgraph.NewFieldSpec(approvalchain.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`migrations: missing "ApprovalChain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approvalchain.FieldID)
		for _, f := range fields {
			if !approvalchain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("migrations: invalid field %q for query", f)}
			}
			if f != approvalchain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(approvalchain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(approvalchain.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(approvalchain.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(approvalchain.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(approvalchain.FieldChain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalchain.FieldChain, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalchain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(approvalchain.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(approvalchain.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(approvalchain.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(approvalchain.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(approvalchain.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(approvalchain.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(approvalchain.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalchain.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ApprovalChain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalchain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
