// Code generated by ent, DO NOT EDIT.

package migrations

import (
	"fmt"
	"itsm-backend/migrations/department"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Department is the model entity for the Department schema.
type Department struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 部门名称
	Name string `json:"name,omitempty"`
	// 部门代码
	Code string `json:"code,omitempty"`
	// 部门描述
	Description string `json:"description,omitempty"`
	// 部门经理ID
	ManagerID int `json:"manager_id,omitempty"`
	// 父部门ID
	ParentID int `json:"parent_id,omitempty"`
	// 租户ID
	TenantID int `json:"tenant_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepartmentQuery when eager-loading is set.
	Edges        DepartmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DepartmentEdges holds the relations/edges for other nodes in the graph.
type DepartmentEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Department `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Department `json:"children,omitempty"`
	// 部门成员
	Users []*User `json:"users,omitempty"`
	// 部门工单
	Tickets []*Ticket `json:"tickets,omitempty"`
	// 部门工作流
	Workflows []*Workflow `json:"workflows,omitempty"`
	// 部门工单分类
	Categories []*TicketCategory `json:"categories,omitempty"`
	// 部门项目
	Projects []*Project `json:"projects,omitempty"`
	// 部门标签
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepartmentEdges) ParentOrErr() (*Department, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: department.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) ChildrenOrErr() ([]*Department, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// TicketsOrErr returns the Tickets value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) TicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[3] {
		return e.Tickets, nil
	}
	return nil, &NotLoadedError{edge: "tickets"}
}

// WorkflowsOrErr returns the Workflows value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) WorkflowsOrErr() ([]*Workflow, error) {
	if e.loadedTypes[4] {
		return e.Workflows, nil
	}
	return nil, &NotLoadedError{edge: "workflows"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) CategoriesOrErr() ([]*TicketCategory, error) {
	if e.loadedTypes[5] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[6] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[7] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Department) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case department.FieldID, department.FieldManagerID, department.FieldParentID, department.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case department.FieldName, department.FieldCode, department.FieldDescription:
			values[i] = new(sql.NullString)
		case department.FieldCreatedAt, department.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Department fields.
func (_m *Department) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case department.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case department.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case department.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case department.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case department.FieldManagerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manager_id", values[i])
			} else if value.Valid {
				_m.ManagerID = int(value.Int64)
			}
		case department.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = int(value.Int64)
			}
		case department.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case department.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case department.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Department.
// This includes values selected through modifiers, order, etc.
func (_m *Department) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Department entity.
func (_m *Department) QueryParent() *DepartmentQuery {
	return NewDepartmentClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Department entity.
func (_m *Department) QueryChildren() *DepartmentQuery {
	return NewDepartmentClient(_m.config).QueryChildren(_m)
}

// QueryUsers queries the "users" edge of the Department entity.
func (_m *Department) QueryUsers() *UserQuery {
	return NewDepartmentClient(_m.config).QueryUsers(_m)
}

// QueryTickets queries the "tickets" edge of the Department entity.
func (_m *Department) QueryTickets() *TicketQuery {
	return NewDepartmentClient(_m.config).QueryTickets(_m)
}

// QueryWorkflows queries the "workflows" edge of the Department entity.
func (_m *Department) QueryWorkflows() *WorkflowQuery {
	return NewDepartmentClient(_m.config).QueryWorkflows(_m)
}

// QueryCategories queries the "categories" edge of the Department entity.
func (_m *Department) QueryCategories() *TicketCategoryQuery {
	return NewDepartmentClient(_m.config).QueryCategories(_m)
}

// QueryProjects queries the "projects" edge of the Department entity.
func (_m *Department) QueryProjects() *ProjectQuery {
	return NewDepartmentClient(_m.config).QueryProjects(_m)
}

// QueryTags queries the "tags" edge of the Department entity.
func (_m *Department) QueryTags() *TagQuery {
	return NewDepartmentClient(_m.config).QueryTags(_m)
}

// Update returns a builder for updating this Department.
// Note that you need to call Department.Unwrap() before calling this method if this Department
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Department) Update() *DepartmentUpdateOne {
	return NewDepartmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Department entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Department) Unwrap() *Department {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("migrations: Department is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Department) String() string {
	var builder strings.Builder
	builder.WriteString("Department(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("manager_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManagerID))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Departments is a parsable slice of Department.
type Departments []*Department
