const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '../src/lib/i18n/translations.ts');
let content = fs.readFileSync(filePath, 'utf8');

const lines = content.split('\n');

let enUSStart = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i] === "  'en-US': {") {
    enUSStart = i;
    break;
  }
}

const dict = {
  '请输入': 'Please enter ',
  '请选择': 'Please select ',
  '新建': 'Create ',
  '编辑': 'Edit ',
  '管理': 'Manage ',
  '总数': 'Total ',
  '成功': 'Success',
  '失败': 'Failed',
  '删除': 'Delete',
  '更新': 'Update',
  '确认': 'Confirm ',
  '系统': 'System ',
  '分配': 'Assign ',
  '关联': 'Linked ',
  '已启用': 'Enabled',
  '已禁用': 'Disabled',
  '用户': 'User',
  '用户组': 'Group',
  '角色': 'Role',
  '权限': 'Permission',
  '菜单': 'Menu',
  '团队': 'Team',
  '成员': 'Member',
  '负责人': 'Leader',
  '上级组': 'Parent Group',
  '无上级组': 'No Parent Group',
  '顶级菜单': 'Top Level Menu',
  '隐藏': 'Hidden',
  '显示': 'Visible',
  '外部链接': 'External Link',
  '工作流': 'Workflow',
  '流程': 'Process',
  '审批': 'Approval',
  'SLA': 'SLA',
  '模板': 'Template',
  '升级': 'Escalation',
  '策略': 'Policy',
  '规则': 'Rule',
  '系统配置': 'System Configuration',
  '参数': 'Parameter',
  '连接器': 'Connector',
  '租户': 'Tenant',
  '路由': 'Route',
  '部门': 'Department',
  '继承': 'Inheritance',
  '分派': 'Assignment',
  '自动化': 'Automation',
  '工单': 'Ticket',
  '分类': 'Category',
  '服务目录': 'Service Catalog',
  '目录': 'Catalog',
  '审计': 'Audit',
  '日志': 'Log',
  '操作人': 'Operator',
  '操作': 'Operation',
  '代理': 'Agent',
  '建议': 'Suggestion',
  '置信度': 'Confidence',
  '提示词': 'Prompt',
  '版本': 'Version',
  '接受': 'Accepted',
  '拒绝': 'Rejected',
  '管理': 'Manage',
  '项目': 'Project',
  '安装': 'Installation',
  '应用': 'Application',
  '标签': 'Tag',
  '颜色': 'Color',
  '改进': 'Improvement',
  '监控': 'Monitor',
  '仪表盘': 'Dashboard',
  '达成率': 'Achievement Rate',
  '即将': 'About to',
  '超时': 'Timeout',
  '瓶颈': 'Bottleneck',
  '实例': 'Instance',
  '定义': 'Definition',
  '市场': 'Marketplace',
  '插件': 'Plugin',
  '资产': 'Asset',
  '许可证': 'License',
  '发布': 'Release',
  '评审': 'Review',
  '入职': 'Onboarding',
  '消息': 'Message',
  '中心': 'Center',
  '通用': 'Common',
  '页面': 'Page',
  '按钮': 'Button',
  '字段': 'Field',
  '搜索': 'Search',
  '刷新': 'Refresh',
  '导出': 'Export',
  '导入': 'Import',
  '批量': 'Batch',
  '确定': 'Confirm',
  '取消': 'Cancel',
  '保存': 'Save',
  '提交': 'Submit',
  '返回': 'Back',
  '下一步': 'Next',
  '上一步': 'Previous',
  '完成': 'Complete',
  '关闭': 'Close',
  '打开': 'Open',
  '详情': 'Details',
  '更多': 'More',
  '全部': 'All',
  '暂无': 'No',
  '加载': 'Loading',
  '是': 'Yes',
  '否': 'No',
  '描述': 'Description',
  '代码': 'Code',
  '类型': 'Type',
  '名称': 'Name',
  '标题': 'Title',
  '内容': 'Content',
  '备注': 'Notes',
  '创建人': 'Created By',
  '创建时间': 'Created At',
  '更新人': 'Updated By',
  '更新时间': 'Updated At',
  '操作时间': 'Operation Time',
  '最后登录': 'Last Login',
  '到期时间': 'Expiration Date',
  '开始时间': 'Start Time',
  '结束时间': 'End Time',
  '排序': 'Sort',
  '图标': 'Icon',
  '路径': 'Path',
  '级别': 'Level',
  '条件': 'Condition',
  '动作': 'Action',
  '目标': 'Target',
  '事件': 'Event',
  '状态': 'Status',
  '邮件': 'Email',
  '手机': 'Phone',
  '姓名': 'Full Name',
  '密码': 'Password',
  '组描述': 'Group Description',
  '团队描述': 'Team Description',
  '权限描述': 'Permission Description',
  '审批链描述': 'Approval Chain Description',
  'SLA描述': 'SLA Description',
  '规则描述': 'Rule Description',
  '分类描述': 'Category Description',
  '服务描述': 'Service Description',
  '策略描述': 'Policy Description',
  '模板描述': 'Template Description',
  '参数描述': 'Parameter Description',
  '连接器名称': 'Connector Name',
  '连接器类型': 'Connector Type',
  '健康检查': 'Health Check',
  '健康状态': 'Health Status',
  '租户名称': 'Tenant Name',
  '租户代码': 'Tenant Code',
  '试用': 'Trial',
  '正式': 'Active',
  '过期': 'Expired',
  '路由名称': 'Route Name',
  '路由条件': 'Route Condition',
  '目标流程': 'Target Process',
  '组名称': 'Group Name',
  '组代码': 'Group Code',
  '成员数': 'Member Count',
  '权限名称': 'Permission Name',
  '权限代码': 'Permission Code',
  '菜单名称': 'Menu Name',
  '菜单路径': 'Menu Path',
  '菜单图标': 'Menu Icon',
  '父菜单': 'Parent Menu',
  '工作流名称': 'Workflow Name',
  '工作流代码': 'Workflow Code',
  '流程分类': 'Process Category',
  '关联业务': 'Linked Business',
  '审批链名称': 'Approval Chain Name',
  '审批级别': 'Approval Level',
  '审批人': 'Approver',
  'SLA名称': 'SLA Name',
  'SLA代码': 'SLA Code',
  '响应时间': 'Response Time',
  '解决时间': 'Resolution Time',
  '模板名称': 'Template Name',
  '策略名称': 'Policy Name',
  '升级条件': 'Escalation Condition',
  '升级动作': 'Escalation Action',
  '通知对象': 'Notification Target',
  '升级级别': 'Escalation Level',
  '参数名称': 'Parameter Name',
  '参数值': 'Parameter Value',
  '参数类型': 'Parameter Type',
  '权限类型': 'Permission Type',
  '菜单权限': 'Menu Permission',
  'API权限': 'API Permission',
  '数据权限': 'Data Permission',
  '租户状态': 'Tenant Status',
  '应用名称': 'Application Name',
  '应用代码': 'Application Code',
  '标签名称': 'Tag Name',
  '标签颜色': 'Tag Color',
  '项目名称': 'Project Name',
  '项目代码': 'Project Code',
  '安装名称': 'Installation Name',
  '安装状态': 'Installation Status',
  '改进名称': 'Improvement Name',
  '流程实例': 'Process Instances',
  '实例ID': 'Instance ID',
  '实例名称': 'Instance Name',
  '实例状态': 'Instance Status',
  '流程定义': 'Process Definition',
  '版本号': 'Version Number',
  '发布版本': 'Release Version',
  '审批意见': 'Approval Comment',
  '审批结果': 'Approval Result',
  '通过': 'Approve',
  '驳回': 'Reject',
  '转交': 'Transfer',
  '资产名称': 'Asset Name',
  '资产编号': 'Asset Number',
  '许可证名称': 'License Name',
  '许可证号': 'License Number',
  '发布名称': 'Release Name',
  '评审内容': 'Review Content',
  '入职流程': 'Onboarding Process',
  '消息中心': 'Message Center',
  'AI建议': 'AI Suggestion',
  'IP地址': 'IP Address',
  '用户代理': 'User Agent',
  'MSP名称': 'MSP Name',
  'MSP代码': 'MSP Code',
  '管理租户数': 'Managed Tenants',
  '菜单创建成功': 'Menu created successfully',
  '菜单更新成功': 'Menu updated successfully',
  '菜单删除成功': 'Menu deleted successfully',
  '分类创建成功': 'Category created successfully',
  '分类更新成功': 'Category updated successfully',
  '分类删除成功': 'Category deleted successfully',
  '工单分类': 'Ticket Categories',
  '分配规则': 'Assignment Rules',
  '自动化规则': 'Automation Rules',
  '审批链': 'Approval Chains',
  '工作流定义': 'Workflow Definitions',
  'SLA定义': 'SLA Definitions',
  'SLA模板': 'SLA Templates',
  '升级策略': 'Escalation Policies',
  '服务目录管理': 'Service Catalog Management',
  '审计日志': 'Audit Logs',
  'AI审计': 'AI Audit',
  '应用管理': 'Application Management',
  '标签管理': 'Tag Management',
  '项目管理': 'Project Management',
  '安装管理': 'Installation Management',
  '改进管理': 'Improvement Management',
  'SLA监控': 'SLA Monitor',
  'SLA仪表盘': 'SLA Dashboard',
  '工作流SLA': 'Workflow SLA',
  '瓶颈分析': 'Bottleneck Analysis',
  '版本管理': 'Version Management',
  '自动化': 'Automation',
  '工单审批': 'Ticket Approval',
  '服务请求': 'Service Request',
  '资产管理': 'Asset Management',
  '许可证管理': 'License Management',
  '发布管理': 'Release Management',
  '入职管理': 'Onboarding Management',
  '市场': 'Marketplace',
  '插件市场': 'Plugin Marketplace',
  '角色管理': 'Role Management',
  '用户组管理': 'Group Management',
  '团队管理': 'Team Management',
  '权限管理': 'Permission Management',
  '菜单管理': 'Menu Management',
  '租户管理': 'Tenant Management',
  'MSP管理': 'MSP Management',
  '连接器管理': 'Connector Management',
  '从模板创建': 'Create From Template',
  '应用模板': 'Apply Template',
  '应用': 'Apply',
};

let count = 0;
for (let i = enUSStart; i < lines.length; i++) {
  const line = lines[i];
  let newLine = line;

  const match = newLine.match(/^(\s*)([a-zA-Z_][a-zA-Z0-9_]*):\s*'(.+)'(,?)\s*$/);
  if (!match) continue;
  const [, indent, key, value, comma] = match;
  if (!/[\u4e00-\u9fff]/.test(value)) continue;

  let translated = value;
  for (const [zh, en] of Object.entries(dict)) {
    if (translated.includes(zh)) {
      translated = translated.split(zh).join(en);
    }
  }
  translated = translated.replace(/\s+/g, ' ').trim();
  if (translated.startsWith(' ')) translated = translated.trimStart();

  newLine = `${indent}${key}: '${translated}'${comma}`;
  if (newLine !== line) {
    lines[i] = newLine;
    count++;
  }
}

fs.writeFileSync(filePath, lines.join('\n'));
console.log('Lines fixed:', count);