#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '../src/lib/i18n/translations.ts');
const content = fs.readFileSync(filePath, 'utf8');

const lines = content.split('\n');

const enUSStart = lines.findIndex((l, i) => i > 1000 && l === "  'en-US': {");
let zhCNNewStart = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i] === "    users: {" && i > 1000 && i < enUSStart) {
    zhCNNewStart = i;
    break;
  }
}

if (zhCNNewStart === -1) {
  console.error('Could not find zh-CN users section');
  process.exit(1);
}

let zhCNNewEnd = -1;
for (let i = zhCNNewStart; i < enUSStart; i++) {
  if (lines[i] === '  },' && lines[i + 1] === "  'en-US': {") {
    zhCNNewEnd = i;
    break;
  }
}

if (zhCNNewEnd === -1) {
  console.error('Could not find zh-CN new sections end');
  process.exit(1);
}

const zhCNNewLines = lines.slice(zhCNNewStart, zhCNNewEnd);
console.log('zh-CN new lines:', zhCNNewLines.length, 'from line', zhCNNewStart + 1, 'to', zhCNNewEnd);

const dict = {
  '用户管理': 'User Management',
  '系统用户账户': 'system user accounts',
  '新建用户': 'Create User',
  '编辑用户': 'Edit User',
  '重置密码': 'Reset Password',
  '禁用': 'Disable',
  '启用': 'Enable',
  '用户总数': 'Total Users',
  '活跃': 'Active',
  '未激活': 'Inactive',
  '搜索用户名、姓名或邮箱...': 'Search username, name or email...',
  '用户名': 'Username',
  '姓名': 'Full Name',
  '邮箱': 'Email',
  '手机号': 'Phone',
  '部门': 'Department',
  '角色': 'Role',
  '状态': 'Status',
  '最后登录': 'Last Login',
  '创建时间': 'Created At',
  '全部状态': 'All Status',
  '全部部门': 'All Departments',
  '请输入用户名': 'Please enter username',
  '请输入姓名': 'Please enter full name',
  '请输入邮箱': 'Please enter email',
  '请输入手机号': 'Please enter phone',
  '请输入密码': 'Please enter password',
  '请选择部门': 'Please select department',
  '请选择角色': 'Please select role',
  '用户创建成功': 'User created successfully',
  '创建用户失败': 'Failed to create user',
  '用户更新成功': 'User updated successfully',
  '更新用户失败': 'Failed to update user',
  '用户删除成功': 'User deleted successfully',
  '删除用户失败': 'Failed to delete user',
  '密码重置成功': 'Password reset successfully',
  '密码重置失败': 'Failed to reset password',
  '确认删除用户': 'Confirm Delete User',
  '确定要删除用户 "{name}" 吗？此操作无法撤销。': 'Are you sure you want to delete user "{name}"? This action cannot be undone.',
  '新密码': 'New Password',
  '密码长度至少 8 位': 'Password must be at least 8 characters',
  '密码至少 8 个字符': 'Password must be at least 8 characters',
  '角色管理': 'Role Management',
  '系统角色和权限': 'system roles and permissions',
  '新建角色': 'Create Role',
  '编辑角色': 'Edit Role',
  '角色总数': 'Total Roles',
  '已启用': 'Enabled',
  '已禁用': 'Disabled',
  '搜索角色名称或代码...': 'Search role name or code...',
  '角色名称': 'Role Name',
  '角色代码': 'Role Code',
  '请输入角色描述': 'Please enter role description',
  '权限': 'Permissions',
  '分配权限': 'Assign Permissions',
  '关联用户': 'Linked Users',
  '角色创建成功': 'Role created successfully',
  '角色更新成功': 'Role updated successfully',
  '角色删除成功': 'Role deleted successfully',
  '请输入角色名称': 'Please enter role name',
  '请输入角色代码': 'Please enter role code',
  '请选择权限': 'Please select permissions',
  '用户组管理': 'Group Management',
  '管理用户组与组织结构': 'manage user groups and org structure',
  '新建用户组': 'Create Group',
  '编辑用户组': 'Edit Group',
  '组名称': 'Group Name',
  '组代码': 'Group Code',
  '上级组': 'Parent Group',
  '成员数': 'Member Count',
  '负责人': 'Leader',
  '组描述': 'Group Description',
  '无上级组': 'No Parent Group',
  '用户组创建成功': 'Group created successfully',
  '用户组更新成功': 'Group updated successfully',
  '用户组删除成功': 'Group deleted successfully',
  '团队管理': 'Team Management',
  '管理企业团队': 'manage enterprise teams',
  '新建团队': 'Create Team',
  '编辑团队': 'Edit Team',
  '团队名称': 'Team Name',
  '团队代码': 'Team Code',
  '团队描述': 'Team Description',
  '成员': 'Members',
  '团队创建成功': 'Team created successfully',
  '团队更新成功': 'Team updated successfully',
  '团队删除成功': 'Team deleted successfully',
  '权限管理': 'Permission Management',
  '管理权限和访问控制': 'manage permissions and access control',
  '新建权限': 'Create Permission',
  '编辑权限': 'Edit Permission',
  '权限名称': 'Permission Name',
  '权限代码': 'Permission Code',
  '权限类型': 'Permission Type',
  '菜单权限': 'Menu Permission',
  'API权限': 'API Permission',
  '数据权限': 'Data Permission',
  '权限创建成功': 'Permission created successfully',
  '权限更新成功': 'Permission updated successfully',
  '权限删除成功': 'Permission deleted successfully',
  '菜单管理': 'Menu Management',
  '管理系统菜单': 'manage system menus',
  '新建菜单': 'Create Menu',
  '编辑菜单': 'Edit Menu',
  '菜单名称': 'Menu Name',
  '菜单路径': 'Menu Path',
  '菜单图标': 'Menu Icon',
  '排序': 'Sort Order',
  '父菜单': 'Parent Menu',
  '顶级菜单': 'Top Level Menu',
  '隐藏': 'Hidden',
  '显示': 'Visible',
  '外部链接': 'External Link',
  '菜单创建成功': 'Menu created successfully',
  '菜单更新成功': 'Menu updated successfully',
  '菜单删除成功': 'Menu deleted successfully',
  '工作流定义': 'Workflow Definitions',
  '管理工作流模板': 'manage workflow templates',
  '新建工作流': 'Create Workflow',
  '编辑工作流': 'Edit Workflow',
  '工作流名称': 'Workflow Name',
  '工作流代码': 'Workflow Code',
  '流程分类': 'Process Category',
  '关联业务': 'Linked Business',
  '工作流创建成功': 'Workflow created successfully',
  '工作流更新成功': 'Workflow updated successfully',
  '工作流删除成功': 'Workflow deleted successfully',
  '审批链': 'Approval Chains',
  '管理审批链规则': 'manage approval chain rules',
  '新建审批链': 'Create Approval Chain',
  '编辑审批链': 'Edit Approval Chain',
  '审批链名称': 'Approval Chain Name',
  '审批链描述': 'Approval Chain Description',
  '审批级别': 'Approval Level',
  '审批人': 'Approver',
  '审批链创建成功': 'Approval chain created successfully',
  '审批链更新成功': 'Approval chain updated successfully',
  '审批链删除成功': 'Approval chain deleted successfully',
  'SLA定义': 'SLA Definitions',
  '管理SLA策略': 'manage SLA policies',
  '新建SLA': 'Create SLA',
  '编辑SLA': 'Edit SLA',
  'SLA名称': 'SLA Name',
  'SLA代码': 'SLA Code',
  '优先级': 'Priority',
  '响应时间(分钟)': 'Response Time (min)',
  '解决时间(分钟)': 'Resolution Time (min)',
  'SLA描述': 'SLA Description',
  'SLA创建成功': 'SLA created successfully',
  'SLA更新成功': 'SLA updated successfully',
  'SLA删除成功': 'SLA deleted successfully',
  'SLA模板': 'SLA Templates',
  '管理SLA模板': 'manage SLA templates',
  '新建SLA模板': 'Create SLA Template',
  '编辑SLA模板': 'Edit SLA Template',
  '模板名称': 'Template Name',
  '模板描述': 'Template Description',
  '从模板创建': 'Create From Template',
  '升级策略': 'Escalation Policies',
  '管理SLA升级策略': 'manage SLA escalation policies',
  '新建升级策略': 'Create Escalation Policy',
  '编辑升级策略': 'Edit Escalation Policy',
  '策略名称': 'Policy Name',
  '升级条件': 'Escalation Condition',
  '升级动作': 'Escalation Action',
  '通知对象': 'Notification Target',
  '升级延迟(分钟)': 'Escalation Delay (min)',
  '升级级别': 'Escalation Level',
  '策略描述': 'Policy Description',
  '系统配置': 'System Configuration',
  '配置系统参数': 'configure system parameters',
  '参数名称': 'Parameter Name',
  '参数值': 'Parameter Value',
  '参数描述': 'Parameter Description',
  '参数类型': 'Parameter Type',
  '配置更新成功': 'Configuration updated successfully',
  '连接器管理': 'Connector Management',
  '管理第三方连接器': 'manage third-party connectors',
  '安装连接器': 'Install Connector',
  '配置连接器': 'Configure Connector',
  '连接器名称': 'Connector Name',
  '连接器类型': 'Connector Type',
  '连接器状态': 'Connector Status',
  '健康检查': 'Health Check',
  '健康状态': 'Health Status',
  '连接器创建成功': 'Connector created successfully',
  '连接器更新成功': 'Connector updated successfully',
  '连接器删除成功': 'Connector deleted successfully',
  '租户管理': 'Tenant Management',
  '管理租户': 'manage tenants',
  '新建租户': 'Create Tenant',
  '编辑租户': 'Edit Tenant',
  '租户名称': 'Tenant Name',
  '租户代码': 'Tenant Code',
  '租户状态': 'Tenant Status',
  '试用': 'Trial',
  '正式': 'Active',
  '过期': 'Expired',
  '到期时间': 'Expiration Date',
  '租户创建成功': 'Tenant created successfully',
  '租户更新成功': 'Tenant updated successfully',
  '租户删除成功': 'Tenant deleted successfully',
  '流程路由': 'Process Routing',
  '配置流程路由规则': 'configure process routing rules',
  '新建路由': 'Create Route',
  '编辑路由': 'Edit Route',
  '路由名称': 'Route Name',
  '路由条件': 'Route Condition',
  '目标流程': 'Target Process',
  '部门流程': 'Department Processes',
  '部门专属流程': 'department-specific processes',
  '新建部门流程': 'Create Department Process',
  '编辑部门流程': 'Edit Department Process',
  '配置继承': 'Configuration Inheritance',
  '部门配置继承': 'department configuration inheritance',
  '继承自': 'Inherited From',
  '继承设置': 'Inheritance Settings',
  '覆盖配置': 'Override Configuration',
  '分派规则': 'Assignment Rules',
  '自动分派规则': 'auto-assignment rules',
  '新建分派规则': 'Create Assignment Rule',
  '编辑分派规则': 'Edit Assignment Rule',
  '规则名称': 'Rule Name',
  '规则条件': 'Rule Condition',
  '分派人': 'Assignee',
  '规则描述': 'Rule Description',
  '自动化规则': 'Automation Rules',
  '自动化触发器': 'automation triggers',
  '新建自动化规则': 'Create Automation Rule',
  '编辑自动化规则': 'Edit Automation Rule',
  '触发事件': 'Trigger Event',
  '触发条件': 'Trigger Condition',
  '执行动作': 'Action',
  '工单分类': 'Ticket Categories',
  '管理工单分类': 'manage ticket categories',
  '新建分类': 'Create Category',
  '编辑分类': 'Edit Category',
  '分类名称': 'Category Name',
  '分类代码': 'Category Code',
  '分类描述': 'Category Description',
  '服务目录': 'Service Catalogs',
  '管理服务目录': 'manage service catalogs',
  '新建服务目录': 'Create Service Catalog',
  '编辑服务目录': 'Edit Catalog',
  '目录名称': 'Catalog Name',
  '目录描述': 'Catalog Description',
  '目录创建成功': 'Catalog created successfully',
  '目录更新成功': 'Catalog updated successfully',
  '目录删除成功': 'Catalog deleted successfully',
  '审计日志': 'Audit Logs',
  '查看审计日志': 'view audit logs',
  '日志类型': 'Log Type',
  '操作人': 'Operator',
  '操作时间': 'Operation Time',
  '操作内容': 'Operation Content',
  'IP地址': 'IP Address',
  '用户代理': 'User Agent',
  'AI审计': 'AI Audit',
  'AI决策审计': 'AI decision audit',
  'AI建议': 'AI Suggestion',
  '置信度': 'Confidence',
  '模型': 'Model',
  '提示词版本': 'Prompt Version',
  '已接受': 'Accepted',
  '已拒绝': 'Rejected',
  'MSP管理': 'MSP Management',
  'MSP合作伙伴': 'MSP partners',
  '新建MSP': 'Create MSP',
  '编辑MSP': 'Edit MSP',
  'MSP名称': 'MSP Name',
  'MSP代码': 'MSP Code',
  '管理租户数': 'Managed Tenants',
  '应用管理': 'Application Management',
  '管理应用': 'manage applications',
  '应用名称': 'Application Name',
  '应用代码': 'Application Code',
  '应用创建成功': 'Application created successfully',
  '应用更新成功': 'Application updated successfully',
  '应用删除成功': 'Application deleted successfully',
  '标签管理': 'Tag Management',
  '管理标签': 'manage tags',
  '新建标签': 'Create Tag',
  '编辑标签': 'Edit Tag',
  '标签名称': 'Tag Name',
  '标签颜色': 'Tag Color',
  '标签创建成功': 'Tag created successfully',
  '标签更新成功': 'Tag updated successfully',
  '标签删除成功': 'Tag deleted successfully',
  '项目管理': 'Project Management',
  '管理项目': 'manage projects',
  '新建项目': 'Create Project',
  '编辑项目': 'Edit Project',
  '项目名称': 'Project Name',
  '项目代码': 'Project Code',
  '项目创建成功': 'Project created successfully',
  '项目更新成功': 'Project updated successfully',
  '项目删除成功': 'Project deleted successfully',
  '安装管理': 'Installation Management',
  '管理安装': 'manage installations',
  '安装名称': 'Installation Name',
  '安装状态': 'Installation Status',
  '改进管理': 'Improvement Management',
  '管理改进项': 'manage improvements',
  '改进名称': 'Improvement Name',
  'SLA监控': 'SLA Monitor',
  '实时监控SLA': 'monitor SLA in real time',
  'SLA仪表盘': 'SLA Dashboard',
  'SLA达成率': 'SLA Achievement Rate',
  '即将超时': 'About to Timeout',
  '已超时': 'Timeout',
  '工作流SLA': 'Workflow SLA',
  '工作流SLA监控': 'workflow SLA monitoring',
  '瓶颈分析': 'Bottleneck Analysis',
  '分析流程瓶颈': 'analyze process bottlenecks',
  '流程实例': 'Process Instances',
  '查看流程实例': 'view process instances',
  '实例ID': 'Instance ID',
  '实例名称': 'Instance Name',
  '流程定义': 'Process Definition',
  '实例状态': 'Instance Status',
  '开始时间': 'Start Time',
  '结束时间': 'End Time',
  '版本管理': 'Version Management',
  '管理流程版本': 'manage process versions',
  '版本号': 'Version',
  '发布版本': 'Release Version',
  '自动化': 'Automation',
  '自动化任务': 'automation tasks',
  '工单审批': 'Ticket Approval',
  '工单审批流程': 'ticket approval workflow',
  '审批': 'Approval',
  '审批记录': 'Approval Records',
  '审批意见': 'Approval Comment',
  '审批结果': 'Approval Result',
  '通过': 'Approve',
  '驳回': 'Reject',
  '转交': 'Transfer',
  '市场': 'Marketplace',
  '插件市场': 'Plugin Marketplace',
  '浏览市场': 'Browse Marketplace',
  '服务请求': 'Service Request',
  '管理服务请求': 'manage service requests',
  '新建服务请求': 'Create Service Request',
  '资产': 'Assets',
  '资产管理': 'Asset Management',
  '管理资产': 'manage assets',
  '资产名称': 'Asset Name',
  '资产编号': 'Asset Number',
  '许可证': 'Licenses',
  '许可证管理': 'License Management',
  '管理许可证': 'manage licenses',
  '许可证名称': 'License Name',
  '许可证号': 'License Number',
  '发布管理': 'Release Management',
  '管理发布': 'manage releases',
  '发布名称': 'Release Name',
  'PIR': 'PIR',
  '实施后评审': 'Post-Implementation Review',
  '评审内容': 'Review Content',
  '入职': 'Onboarding',
  '入职管理': 'Onboarding Management',
  '入职流程': 'Onboarding Process',
  '消息': 'Messages',
  '消息中心': 'Message Center',
  '页面': 'Page',
  '通用': 'Common',
  '状态通用': 'Status Common',
  '操作通用': 'Actions Common',
  '字段通用': 'Fields Common',
  '按钮通用': 'Buttons Common',
  '搜索': 'Search',
  '刷新': 'Refresh',
  '导出': 'Export',
  '导入': 'Import',
  '批量删除': 'Batch Delete',
  '确认删除': 'Confirm Delete',
  '确定': 'Confirm',
  '取消': 'Cancel',
  '保存': 'Save',
  '提交': 'Submit',
  '返回': 'Back',
  '下一步': 'Next',
  '上一步': 'Previous',
  '完成': 'Complete',
  '关闭': 'Close',
  '打开': 'Open',
  '详情': 'Details',
  '编辑': 'Edit',
  '删除': 'Delete',
  '创建': 'Create',
  '更新': 'Update',
  '操作': 'Actions',
  '更多': 'More',
  '全部': 'All',
  '暂无数据': 'No Data',
  '加载中...': 'Loading...',
  '成功': 'Success',
  '失败': 'Failed',
  '是': 'Yes',
  '否': 'No',
  '是': 'Yes',
  '描述': 'Description',
  '代码': 'Code',
  '类型': 'Type',
  '名称': 'Name',
  '标题': 'Title',
  '内容': 'Content',
  '备注': 'Notes',
  '创建人': 'Created By',
  '更新人': 'Updated By',
  '更新时间': 'Updated At',
};

function translate(line) {
  const match = line.match(/^(\s*)([a-zA-Z_][a-zA-Z0-9_]*):\s*'([^']*)',?\s*$/);
  if (!match) return line;
  const [, indent, key, value] = match;
  let translated = value;
  for (const [zh, en] of Object.entries(dict)) {
    if (translated === zh) {
      translated = en;
      break;
    }
    if (translated.includes(zh)) {
      translated = translated.split(zh).join(en);
    }
  }
  return `${indent}${key}: '${translated}',`;
}

const enUSLines = zhCNNewLines.map(translate);

const outPath = path.resolve(__dirname, '../en_us_new_sections.txt');
fs.writeFileSync(outPath, enUSLines.join('\n'));
console.log('en-US new sections written to', outPath);
console.log('Lines:', enUSLines.length);