#!/usr/bin/env node
const fs = require('fs');

const filePath = '/Users/heidsoft/Downloads/research/itsm/itsm-frontend/src/lib/i18n/translations.ts';
let content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

// Step 1: Insert zh-CN sections before line 1070 (the outer closing of zh-CN)
// The structure is: line 1069 is `    },` (closes auth), line 1070 is `  },` (closes outer zh-CN)
// We want to insert AFTER line 1069 and BEFORE line 1070

// But `sed` would shift line numbers. So we need to do this in one pass with string operations.
const newSectionsZhCN = `# ============================================================
// New: User Management / Role Management / Group Management
// ============================================================
    users: {
      title: '用户管理',
      description: '管理系统用户账户',
      create: '新建用户',
      edit: '编辑用户',
      resetPassword: '重置密码',
      disable: '禁用',
      enable: '启用',
      total: '用户总数',
      active: '活跃',
      inactive: '未激活',
      searchPlaceholder: '搜索用户名、姓名或邮箱...',
      username: '用户名',
      fullName: '姓名',
      email: '邮箱',
      phone: '手机号',
      department: '部门',
      role: '角色',
      status: '状态',
      lastLogin: '最后登录',
      createdAt: '创建时间',
      allStatus: '全部状态',
      allDepartments: '全部部门',
      activeUser: '活跃',
      inactiveUser: '未激活',
      enterUsername: '请输入用户名',
      enterFullName: '请输入姓名',
      enterEmail: '请输入邮箱',
      enterPhone: '请输入手机号',
      enterPassword: '请输入密码',
      selectDepartment: '请选择部门',
      selectRole: '请选择角色',
      createSuccess: '用户创建成功',
      createFailed: '创建用户失败',
      updateSuccess: '用户更新成功',
      updateFailed: '更新用户失败',
      deleteSuccess: '用户删除成功',
      deleteFailed: '删除用户失败',
      resetPasswordSuccess: '密码重置成功',
      resetPasswordFailed: '密码重置失败',
      confirmDelete: '确认删除用户',
      confirmDeleteContent: '确定要删除用户 "{name}" 吗？此操作无法撤销。',
      newPassword: '新密码',
      passwordHint: '密码长度至少 8 位',
      minPasswordLength: '密码至少 8 个字符',
    },
    // 角色管理
    roles: {
      title: '角色管理',
      description: '管理系统角色和权限',
      create: '新建角色',
      edit: '编辑角色',
      total: '角色总数',
      enabled: '已启用',
      disabled: '已禁用',
      searchPlaceholder: '搜索角色名称或代码...',
      roleName: '角色名称',
      roleCode: '角色代码',
      roleDescription: '角色描述',
      permissions: '权限',
      assignPermissions: '分配权限',
      userCount: '关联用户',
      createSuccess: '角色创建成功',
      updateSuccess: '角色更新成功',
      deleteSuccess: '角色删除成功',
      enterRoleName: '请输入角色名称',
      enterRoleCode: '请输入角色代码',
      selectPermissions: '请选择权限',
    },
    // 用户组管理
    groups: {
      title: '用户组管理',
      description: '管理用户组与组织结构',
      create: '新建用户组',
      edit: '编辑用户组',
      groupName: '组名称',
      groupCode: '组代码',
      parentGroup: '上级组',
      memberCount: '成员数',
      leader: '负责人',
      groupDescription: '组描述',
      noParent: '无上级组',
      createSuccess: '用户组创建成功',
      updateSuccess: '用户组更新成功',
      deleteSuccess: '用户组删除成功',
    },
    // 团队管理
    teamsPage: {
      title: '团队管理',
      description: '管理企业团队',
      create: '新建团队',
      edit: '编辑团队',
      teamName: '团队名称',
      teamCode: '团队代码',
      teamDescription: '团队描述',
      manager: '负责人',
      members: '成员',
      memberCount: '成员数',
      createSuccess: '团队创建成功',
      updateSuccess: '团队更新成功',
      deleteSuccess: '团队删除成功',
      enterTeamName: '请输入团队名称',
      enterTeamCode: '请输入团队代码',
      selectManager: '请选择负责人',
    },
    // 权限管理
    permissions: {
      title: '权限配置',
      description: '配置系统权限矩阵',
      permissionCode: '权限代码',
      permissionName: '权限名称',
      module: '所属模块',
      type: '权限类型',
      permissionDescription: '权限描述',
      menu: '菜单权限',
      button: '按钮权限',
      api: 'API权限',
      data: '数据权限',
      allModules: '全部模块',
      allTypes: '全部类型',
      createSuccess: '权限创建成功',
      updateSuccess: '权限更新成功',
      deleteSuccess: '权限删除成功',
    },
    // 菜单管理
    menus: {
      title: '菜单管理',
      description: '管理系统菜单与导航',
      create: '新建菜单',
      edit: '编辑菜单',
      menuName: '菜单名称',
      menuPath: '路由路径',
      parentMenu: '上级菜单',
      icon: '图标',
      sortOrder: '排序',
      permissionCode: '权限码',
      isEnabled: '启用',
      isVisible: '可见',
      isExternal: '外链',
      component: '组件路径',
      noParent: '无上级菜单',
      selectIcon: '选择图标',
      searchIcon: '搜索图标',
      enabled: '已启用',
      disabled: '已停用',
      visible: '可见',
      hidden: '隐藏',
      loadFailed: '加载菜单列表失败',
      createSuccess: '菜单创建成功',
      updateSuccess: '菜单更新成功',
      deleteSuccess: '菜单删除成功',
      totalMenus: '总菜单数',
      enabledMenus: '已启用菜单',
      disabledMenus: '已禁用菜单',
      hiddenMenus: '已隐藏菜单',
      refresh: '刷新',
      searchPlaceholder: '搜索菜单名称或路径...',
      noPermission: '未配置权限码',
      toggleEnable: '切换启用',
      toggleEnableHint: '切换此菜单的启用状态',
      toggleVisible: '切换可见',
      toggleVisibleHint: '切换此菜单的可见状态',
      editMenu: '编辑菜单项',
      createMenu: '新建菜单项',
      usageTip: '使用提示',
      usageTipLine1: '菜单按树形结构组织；上级菜单用于建立层级关系。',
      usageTipLine2: '权限码用于关联 RBAC 权限；留空表示不限制。',
      usageTipLine3: '隐藏菜单仍可用于路由跳转，但不会在导航中显示。',
    },
    // 工作流模板
    workflowsPage: {
      title: '工作流模板',
      description: '管理 BPMN 流程模板',
      create: '新建工作流',
      edit: '编辑工作流',
      deploy: '部署工作流',
      deactivate: '停用工作流',
      duplicate: '复制工作流',
      import: '导入工作流',
      export: '导出工作流',
      workflowName: '工作流名称',
      workflowCode: '工作流代码',
      category: '分类',
      version: '版本',
      deployed: '已部署',
      notDeployed: '未部署',
      deploySuccess: '部署成功',
      deactivateSuccess: '停用成功',
      duplicateSuccess: '复制成功',
      importSuccess: '导入成功',
      exportSuccess: '导出成功',
      loadFailed: '加载工作流失败',
    },
    // 审批链
    approvalChains: {
      title: '审批链配置',
      description: '配置多级审批流程',
      create: '新建审批链',
      edit: '编辑审批链',
      chainName: '审批链名称',
      chainDescription: '审批链描述',
      level: '审批层级',
      approver: '审批人',
      condition: '触发条件',
      priority: '优先级',
      category: '分类',
      enabled: '启用',
      createSuccess: '审批链创建成功',
      updateSuccess: '审批链更新成功',
      deleteSuccess: '审批链删除成功',
      enterChainName: '请输入审批链名称',
      selectApprover: '请选择审批人',
      addLevel: '添加审批层级',
    },
    // SLA定义
    slaDefinitions: {
      title: 'SLA定义',
      description: '设置服务级别协议',
      create: '新建SLA',
      edit: '编辑SLA',
      slaName: 'SLA名称',
      slaDescription: 'SLA描述',
      priority: '优先级',
      responseTime: '响应时间(分钟)',
      resolveTime: '解决时间(分钟)',
      warningThreshold: '预警阈值(%)',
      enabled: '启用',
      createSuccess: 'SLA创建成功',
      updateSuccess: 'SLA更新成功',
      deleteSuccess: 'SLA删除成功',
      enterSlaName: '请输入SLA名称',
      enterResponseTime: '请输入响应时间',
      enterResolveTime: '请输入解决时间',
    },
    // SLA模板
    slaTemplatesPage: {
      title: 'SLA模板',
      description: 'SLA预设模板库',
      create: '新建模板',
      apply: '应用模板',
      templateName: '模板名称',
      templateType: '模板类型',
      incident: '事件模板',
      change: '变更模板',
      serviceRequest: '服务请求模板',
      preview: '预览',
    },
    // 升级矩阵
    escalationMatrices: {
      title: '升级矩阵',
      description: '配置事件升级矩阵',
      matrixName: '矩阵名称',
      matrixType: '矩阵类型',
      preview: '预览',
      create: '新建矩阵',
      edit: '编辑矩阵',
    },
    // 升级规则
    escalationRulesPage: {
      title: '升级规则',
      description: '配置事件升级策略',
      create: '新建规则',
      edit: '编辑规则',
      ruleName: '规则名称',
      ruleDescription: '规则描述',
      triggerCondition: '触发条件',
      priority: '优先级',
      createSuccess: '规则创建成功',
      updateSuccess: '规则更新成功',
      deleteSuccess: '规则删除成功',
    },
    // 系统配置
    systemConfig: {
      title: '系统配置',
      description: '配置系统运行参数',
      basicConfig: '基础配置',
      emailConfig: '邮件配置',
      smsConfig: '短信配置',
      securityConfig: '安全配置',
      logConfig: '日志配置',
      saveSuccess: '保存成功',
      saveFailed: '保存失败',
    },
    // 连接器
    connectors: {
      title: '连接器',
      description: '管理第三方系统连接器',
      create: '新建连接器',
      edit: '编辑连接器',
      connectorName: '连接器名称',
      connectorType: '连接器类型',
      connectorConfig: '连接器配置',
      healthCheck: '健康检查',
      healthStatus: '健康状态',
      healthy: '正常',
      unhealthy: '异常',
      unknown: '未知',
      enable: '启用连接器',
      disable: '禁用连接器',
      testConnection: '测试连接',
      testSuccess: '测试成功',
      testFailed: '测试失败',
      createSuccess: '连接器创建成功',
      updateSuccess: '连接器更新成功',
      deleteSuccess: '连接器删除成功',
    },
    // 租户管理
    tenants: {
      title: '租户管理',
      description: '管理多租户账户',
      create: '新建租户',
      edit: '编辑租户',
      tenantName: '租户名称',
      tenantCode: '租户代码',
      tenantDescription: '租户描述',
      createSuccess: '租户创建成功',
      updateSuccess: '租户更新成功',
      deleteSuccess: '租户删除成功',
    },
    // 流程路由
    processRouting: {
      title: '流程路由',
      description: '配置工单流程路由规则',
      routeName: '路由名称',
      matchCondition: '匹配条件',
      targetProcess: '目标流程',
      create: '新建路由',
      edit: '编辑路由',
      createSuccess: '路由创建成功',
      updateSuccess: '路由更新成功',
      deleteSuccess: '路由删除成功',
    },
    // 部门流程
    departmentProcesses: {
      title: '部门流程',
      description: '按部门配置专属流程',
      department: '部门',
      process: '流程',
      linkedProcess: '关联流程',
      create: '新建',
      edit: '编辑',
      createSuccess: '部门流程创建成功',
      updateSuccess: '部门流程更新成功',
      deleteSuccess: '部门流程删除成功',
    },
    // 配置继承
    configInheritance: {
      title: '配置继承',
      description: '配置父子租户配置继承',
      parentConfig: '父配置',
      childConfig: '子配置',
      inheritancePolicy: '继承策略',
      override: '覆盖',
      merge: '合并',
      inherit: '继承',
      create: '新建',
      edit: '编辑',
      saveSuccess: '保存成功',
      saveFailed: '保存失败',
    },
    // 分配规则
    assignmentRules: {
      title: '分配规则',
      description: '配置工单自动分配',
      ruleName: '规则名称',
      ruleDescription: '规则描述',
      matchCondition: '匹配条件',
      assignmentTarget: '分配目标',
      priority: '优先级',
      enabled: '启用',
      create: '新建规则',
      edit: '编辑规则',
      createSuccess: '规则创建成功',
      updateSuccess: '规则更新成功',
      deleteSuccess: '规则删除成功',
    },
    // 自动化规则
    automationRules: {
      title: '自动化规则',
      description: '配置工单自动化处理',
      ruleName: '规则名称',
      ruleDescription: '规则描述',
      triggerEvent: '触发事件',
      action: '执行动作',
      priority: '优先级',
      enabled: '启用',
      create: '新建规则',
      edit: '编辑规则',
      createSuccess: '规则创建成功',
      updateSuccess: '规则更新成功',
      deleteSuccess: '规则删除成功',
    },
    // 工单分类
    ticketCategories: {
      title: '工单分类',
      description: '管理工单分类目录',
      create: '新建分类',
      edit: '编辑分类',
      categoryName: '分类名称',
      categoryCode: '分类代码',
      parentCategory: '上级分类',
      categoryDescription: '分类描述',
      noParent: '无上级分类',
      createSuccess: '分类创建成功',
      updateSuccess: '分类更新成功',
      deleteSuccess: '分类删除成功',
    },
    // 服务目录管理
    serviceCatalogs: {
      title: '服务目录管理',
      description: '管理服务目录和分类',
      create: '新建服务',
      edit: '编辑服务',
      serviceName: '服务名称',
      category: '分类',
      serviceDescription: '服务描述',
      deliveryTime: '交付时间',
      enabled: '启用',
      createSuccess: '服务创建成功',
      updateSuccess: '服务更新成功',
      deleteSuccess: '服务创建成功',
    },
    // 审计日志
    auditLogs: {
      title: '审计日志',
      description: '查看系统操作审计日志',
      operator: '操作人',
      operationTime: '操作时间',
      operationType: '操作类型',
      operationContent: '操作内容',
      ipAddress: 'IP地址',
      userAgent: '用户代理',
      detail: '详情',
      searchPlaceholder: '搜索操作人、内容...',
      allModules: '全部模块',
    },
    // AI审计
    aiAudit: {
      title: 'AI审计',
      description: '查看 AI 决策审计记录',
      decisionType: '决策类型',
      model: '模型',
      prompt: '提示词',
      response: '响应',
      confidence: '置信度',
      accept: '接受',
      reject: '拒绝',
      searchPlaceholder: '搜索决策类型、模型...',
      allTypes: '全部类型',
    },
    // MSP管理
    msp: {
      title: 'MSP管理',
      description: '管理 MSP 服务提供商',
      serviceProvider: '服务提供商',
      customerTenant: '客户租户',
      serviceLevel: '服务等级',
      create: '新建',
      edit: '编辑',
      createSuccess: 'MSP创建成功',
      updateSuccess: 'MSP更新成功',
      deleteSuccess: 'MSP删除成功',
    },
    // 应用管理
    applications: {
      title: '应用管理',
      description: '管理可安装应用',
      appName: '应用名称',
      appVersion: '应用版本',
      installSource: '安装来源',
      create: '新建',
      edit: '编辑',
      install: '安装',
      uninstall: '卸载',
      createSuccess: '应用创建成功',
      updateSuccess: '应用更新成功',
      deleteSuccess: '应用删除成功',
    },
    // 标签管理
    tags: {
      title: '标签管理',
      description: '管理资源标签',
      tagName: '标签名称',
      tagColor: '标签颜色',
      create: '新建标签',
      edit: '编辑标签',
      createSuccess: '标签创建成功',
      updateSuccess: '标签更新成功',
      deleteSuccess: '标签删除成功',
    },
    // 项目
    projects: {
      title: '项目',
      description: '管理项目空间',
      projectName: '项目名称',
      projectDescription: '项目描述',
      projectMembers: '项目成员',
      projectStatus: '项目状态',
      create: '新建项目',
      edit: '编辑项目',
      createSuccess: '项目创建成功',
      updateSuccess: '项目更新成功',
      deleteSuccess: '项目删除成功',
    },
    // 安装
    installations: {
      title: '安装',
      description: '管理应用安装实例',
      installTime: '安装时间',
      installStatus: '安装状态',
      create: '新建',
      edit: '编辑',
      uninstall: '卸载',
    },
    // 改进建议
    improvements: {
      title: '改进建议',
      description: '管理产品改进建议',
      suggestionTitle: '建议标题',
      suggestionDescription: '建议描述',
      suggestionStatus: '建议状态',
      create: '新建',
      edit: '编辑',
      createSuccess: '建议创建成功',
      updateSuccess: '建议更新成功',
      deleteSuccess: '建议删除成功',
    },
    // SLA监控
    slaMonitor: {
      title: 'SLA监控',
      description: '实时监控 SLA 状态',
      allStatus: '全部状态',
      warning: '预警',
      breached: '已违约',
      within: '正常',
      searchPlaceholder: '搜索工单号、标题...',
    },
    // SLA仪表盘
    slaDashboard: {
      title: 'SLA仪表盘',
      description: 'SLA 监控仪表盘',
      totalSla: 'SLA总数',
      activeSla: '生效中',
      breachedSla: '已违约',
      warningSla: '预警',
      averageResponse: '平均响应时间',
      averageResolve: '平均解决时间',
    },
    // 工作流SLA
    workflowSla: {
      title: '工作流SLA',
      description: '工作流任务 SLA 监控',
      taskName: '任务名称',
      workflowName: '工作流名称',
      slaStatus: 'SLA状态',
      exceededTime: '超出时间',
      searchPlaceholder: '搜索任务、工作流...',
    },
    // 瓶颈分析
    bottlenecks: {
      title: '瓶颈分析',
      description: '分析流程瓶颈',
      nodeName: '节点名称',
      averageWaitTime: '平均等待时间',
      averageProcessTime: '平均处理时间',
      occurrenceCount: '出现次数',
      searchPlaceholder: '搜索节点名称...',
    },
    // 流程实例
    instances: {
      title: '流程实例',
      description: '流程实例管理',
      instanceId: '实例ID',
      workflowName: '工作流名称',
      instanceStatus: '实例状态',
      startTime: '开始时间',
      endTime: '结束时间',
      initiator: '发起人',
      searchPlaceholder: '搜索实例ID、工作流...',
    },
    // 流程版本
    versions: {
      title: '流程版本',
      description: '管理流程版本',
      versionNumber: '版本号',
      versionNotes: '版本说明',
      publishedAt: '发布时间',
      publisher: '发布人',
      searchPlaceholder: '搜索版本号...',
    },
    // 自动化
    automation: {
      title: '自动化',
      description: '配置自动化规则',
      ruleName: '规则名称',
      ruleDescription: '规则描述',
      triggerEvent: '触发事件',
      action: '执行动作',
      priority: '优先级',
      enabled: '启用',
      create: '新建',
      edit: '编辑',
      createSuccess: '规则创建成功',
      updateSuccess: '规则更新成功',
      deleteSuccess: '规则删除成功',
    },
    // 工单审批
    ticketApproval: {
      title: '工单审批',
      description: '工单审批流程',
      pending: '待审批',
      approved: '已通过',
      rejected: '已驳回',
      approvalComment: '审批意见',
      approver: '审批人',
      approvalTime: '审批时间',
      approve: '审批通过',
      reject: '审批驳回',
      searchPlaceholder: '搜索工单号、标题...',
    },
    // 审批
    approvals: {
      title: '审批',
      description: '审批中心',
      pending: '待审批',
      approved: '已通过',
      rejected: '已驳回',
      all: '全部',
      myApproval: '我的审批',
      searchPlaceholder: '搜索审批单...',
    },
    // 应用市场
    marketplace: {
      title: '应用市场',
      description: '浏览应用市场',
      appName: '应用名称',
      appDescription: '应用描述',
      appVersion: '应用版本',
      install: '安装',
      installed: '已安装',
      category: '分类',
      developer: '开发者',
      searchPlaceholder: '搜索应用名...',
    },
    // 服务请求
    serviceRequests: {
      title: '服务请求',
      description: '服务请求管理',
      requestNumber: '请求编号',
      requester: '请求人',
      requestTime: '请求时间',
      requestStatus: '请求状态',
      serviceName: '服务名称',
      searchPlaceholder: '搜索请求编号...',
    },
    // 资产
    assets: {
      title: '资产',
      description: '资产管理',
      assetName: '资产名称',
      assetNumber: '资产编号',
      assetCategory: '资产品类',
      assetStatus: '资产状态',
      searchPlaceholder: '搜索资产名称、编号...',
    },
    // 许可证
    licenses: {
      title: '许可证',
      description: '许可证管理',
      licenseName: '许可证名称',
      licenseKey: '许可证密钥',
      expirationDate: '过期时间',
      assigned: '已分配',
      unassigned: '未分配',
      searchPlaceholder: '搜索许可证名称...',
    },
    // 发布
    releases: {
      title: '发布',
      description: '发布管理',
      releaseName: '发布名称',
      releaseVersion: '发布版本',
      releaseDate: '发布日期',
      releaseStatus: '发布状态',
      searchPlaceholder: '搜索发布名称...',
    },
    // PIR
    pir: {
      title: 'PIR',
      description: '实施后评审',
      reviewContent: '评审内容',
      reviewResult: '评审结果',
      reviewer: '评审人',
      reviewTime: '评审时间',
      searchPlaceholder: '搜索PIR内容...',
    },
    // 入职
    onboarding: {
      title: '入职',
      description: '入职管理',
      onboardingPerson: '入职人员',
      onboardingDate: '入职日期',
      onboardingStatus: '入职状态',
      searchPlaceholder: '搜索入职人员...',
    },
    // 消息
    messages: {
      title: '消息',
      description: '消息中心',
      unread: '未读',
      read: '已读',
      all: '全部',
      markRead: '标记已读',
      markAllRead: '全部已读',
      searchPlaceholder: '搜索消息...',
    },
    // 通用页面
    page: {
      title: '页面',
      description: '通用页面',
      loading: '加载中',
      empty: '暂无数据',
      loadFailed: '加载失败',
      retry: '重试',
    },
    // 通用状态
    statusCommon: {
      title: '通用状态',
      draft: '草稿',
      pending: '待处理',
      processing: '处理中',
      completed: '已完成',
      cancelled: '已取消',
      closed: '已关闭',
    },
    // 通用按钮
    buttonsCommon: {
      title: '通用按钮',
      search: '搜索',
      reset: '重置',
      confirm: '确认',
      cancel: '取消',
      back: '返回',
      next: '下一步',
      previous: '上一步',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      create: '创建',
      submit: '提交',
      export: '导出',
      import: '导入',
    },
    // 通用字段
    fieldsCommon: {
      title: '通用字段',
      name: '名称',
      code: '代码',
      description: '描述',
      type: '类型',
      status: '状态',
      creator: '创建人',
      createdAt: '创建时间',
      updater: '更新人',
      updatedAt: '更新时间',
      actions: '操作',
      enabled: '启用',
      yes: '是',
      no: '否',
    },
`;

// Save the new zh-CN sections to a file
fs.writeFileSync('/Users/heidsoft/Downloads/research/itsm/itsm-frontend/zh_cn_new_sections.txt', newSectionsZhCN);
console.log('zh-CN new sections saved');
console.log('zh-CN section lines:', newSectionsZhCN.split('\n').length);
